### ISSUE TITLE
npe in v0.7

### ISSUE THREAD

**Issue by liudongmiao** [liudongmiao/Brevent#107]
```
02-21 15:35:18.616 11259 11277 E AndroidRuntime: FATAL EXCEPTION: Brevent
02-21 15:35:18.616 11259 11277 E AndroidRuntime: Process: me.piebridge.brevent, PID: 11259
02-21 15:35:18.616 11259 11277 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.os.Handler.sendEmptyMessage(int)' on a null object reference
02-21 15:35:18.616 11259 11277 E AndroidRuntime: 	at me.piebridge.brevent.ui.BreventActivity.a(BreventActivity.java:541)
02-21 15:35:18.616 11259 11277 E AndroidRuntime: 	at me.piebridge.brevent.ui.BreventActivity.a(BreventActivity.java:495)
02-21 15:35:18.616 11259 11277 E AndroidRuntime: 	at me.piebridge.brevent.ui.a.handleMessage(AppsActivityHandler.java:55)
02-21 15:35:18.616 11259 11277 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
02-21 15:35:18.616 11259 11277 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:154)
02-21 15:35:18.616 11259 11277 E AndroidRuntime: 	at android.os.HandlerThread.run(HandlerThread.java:61)
```

**Comment by liudongmiao** [comment]
```
02-21 15:36:40.701 13553 13553 E AndroidRuntime: FATAL EXCEPTION: main
02-21 15:36:40.701 13553 13553 E AndroidRuntime: Process: me.piebridge.brevent, PID: 13553
02-21 15:36:40.701 13553 13553 E AndroidRuntime: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
02-21 15:36:40.701 13553 13553 E AndroidRuntime: 	at java.util.ArrayList.get(ArrayList.java:411)
02-21 15:36:40.701 13553 13553 E AndroidRuntime: 	at me.piebridge.brevent.ui.j.a(AppsItemHandler.java:101)
02-21 15:36:40.701 13553 13553 E AndroidRuntime: 	at me.piebridge.brevent.ui.j.handleMessage(AppsItemHandler.java:43)
02-21 15:36:40.701 13553 13553 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
02-21 15:36:40.701 13553 13553 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:154)
02-21 15:36:40.701 13553 13553 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6119)
02-21 15:36:40.701 13553 13553 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
02-21 15:36:40.701 13553 13553 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
02-21 15:36:40.701 13553 13553 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
```
