### ISSUE TITLE
作者能不能出一个打到CyanogenMod源码里的补丁？

### ISSUE THREAD

**Issue by pexcn** [liudongmiao/Brevent#11]
然后直接编译一个rom就能直接用『黑域』了而不用从系统提取文件来打补丁。😀

**Comment by aviraxp** [comment]
https://github.com/SudaMod/android_frameworks_base/pull/13

**Comment by pexcn** [comment]
@aviraxp 能移植到cm-13.0吗？

**Comment by aviraxp** [comment]
当然可以。

**Comment by luanzun** [comment]
cm14.1 出错了。
`  Traceback (most recent call last):
  File "E:\oneplus2\heiyu\patch.py", line 315, in <module>
    main()
  File "E:\oneplus2\heiyu\patch.py", line 311, in main
    ActivityManagerService(options.dir_services, options.dir_apk).run()
  File "E:\oneplus2\heiyu\patch.py", line 147, in __init__
    self.methods = self.init_pr_methods()
  File "E:\oneplus2\heiyu\patch.py", line 156, in init_pr_methods
    for line in open(path, "r"):`
