### ISSUE TITLE
cannot listen port - 没有网络权限

### ISSUE THREAD

**Issue by wangdong268** [liudongmiao/Brevent#114]
换了几个机器都不行。
```
[dowang@dowang-laptop ~]$ adb -d shell
angler:/ # shell /data/app/me.piebridge.brevent-1/lib/arm/libbootstrap.so
/system/bin/sh: shell: not found
127|angler:/ # /data/app/me.piebridge.brevent-1/lib/arm/libbootstrap.so
please run with 'su shell /data/app/me.piebridge.brevent-1/lib/arm/libbootstrap.so'
angler:/ # su shell /data/app/me.piebridge.brevent-1/lib/arm/libbootstrap.so   
checking.............
cannot listen port, please report bug to https://github.com/liudongmiao/Brevent/issues with log below
--- crash start ---
02-23 10:22:10.857 12700 12709 E AndroidRuntime: *** FATAL EXCEPTION IN SYSTEM PROCESS: Thread-1
02-23 10:22:10.857 12700 12709 E AndroidRuntime: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
02-23 10:22:10.857 12700 12709 E AndroidRuntime: 	at me.piebridge.brevent.loader.Brevent.run(Brevent.java:60)
02-23 10:22:10.857 12700 12709 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:761)
02-23 10:22:10.857 12700 12709 E AndroidRuntime: Caused by: java.lang.reflect.InvocationTargetException
02-23 10:22:10.857 12700 12709 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
02-23 10:22:10.857 12700 12709 E AndroidRuntime: 	at me.piebridge.brevent.loader.Brevent.run(Brevent.java:57)
02-23 10:22:10.857 12700 12709 E AndroidRuntime: 	... 1 more
02-23 10:22:10.857 12700 12709 E AndroidRuntime: Caused by: java.net.SocketException: Permission denied
02-23 10:22:10.857 12700 12709 E AndroidRuntime: 	at java.net.ServerSocket.createImpl(ServerSocket.java:309)
02-23 10:22:10.857 12700 12709 E AndroidRuntime: 	at java.net.ServerSocket.getImpl(ServerSocket.java:258)
02-23 10:22:10.857 12700 12709 E AndroidRuntime: 	at java.net.ServerSocket.bind(ServerSocket.java:377)
02-23 10:22:10.857 12700 12709 E AndroidRuntime: 	at java.net.ServerSocket.<init>(ServerSocket.java:237)
02-23 10:22:10.857 12700 12709 E AndroidRuntime: 	at me.piebridge.brevent.server.BreventServer.main(BreventServer.java:849)
02-23 10:22:10.857 12700 12709 E AndroidRuntime: 	... 3 more
--- crash end ---
--- brevent start ---
02-23 10:22:10.639 12700 12700 D BreventLoader: lib: /data/user_de/0/com.android.shell/brevent, loader: /data/user_de/0/com.android.shell/brevent/libloader.so
02-23 10:22:10.645 12700 12709 D BreventServer: Brevent Server 0.7 started
02-23 10:22:10.656 12700 12709 D BreventServer: brevent user: 0, uid: 2000
02-23 10:22:10.657 12700 12709 D BreventServer: brevent data directory: /data/user_de/0/com.android.shell
02-23 10:22:10.696 12700 12709 D BreventServer: loaded brevent list
02-23 10:22:10.696 12700 12709 D BreventServer: loaded brevent conf
02-23 10:22:10.754 12700 12709 D BreventServer: checking
02-23 10:22:10.840 12700 12709 I BreventServer: power_screen_state, tag: 2728, event: 7
02-23 10:22:10.841 12700 12709 I BreventServer: notification_cancel_all, tag: 2752, event: 6
02-23 10:22:10.844 12700 12709 I BreventServer: am_new_intent, tag: 30003, event: 2
02-23 10:22:10.845 12700 12709 I BreventServer: am_pause_activity, tag: 30013, event: 3
02-23 10:22:10.845 12700 12709 I BreventServer: am_proc_start, tag: 30014, event: 4
02-23 10:22:10.846 12700 12709 I BreventServer: am_switch_user, tag: 30041, event: 5
02-23 10:22:10.847 12700 12709 I BreventServer: am_focused_activity, tag: 30043, event: 1
02-23 10:22:10.857 12700 12709 D BreventLoader: Can't run brevent server
02-23 10:22:10.857 12700 12709 D BreventLoader: java.lang.reflect.InvocationTargetException
02-23 10:22:10.857 12700 12709 D BreventLoader: 	at java.lang.reflect.Method.invoke(Native Method)
02-23 10:22:10.857 12700 12709 D BreventLoader: 	at me.piebridge.brevent.loader.Brevent.run(Brevent.java:57)
02-23 10:22:10.857 12700 12709 D BreventLoader: 	at java.lang.Thread.run(Thread.java:761)
02-23 10:22:10.857 12700 12709 D BreventLoader: Caused by: java.net.SocketException: Permission denied
02-23 10:22:10.857 12700 12709 D BreventLoader: 	at java.net.ServerSocket.createImpl(ServerSocket.java:309)
02-23 10:22:10.857 12700 12709 D BreventLoader: 	at java.net.ServerSocket.getImpl(ServerSocket.java:258)
02-23 10:22:10.857 12700 12709 D BreventLoader: 	at java.net.ServerSocket.bind(ServerSocket.java:377)
02-23 10:22:10.857 12700 12709 D BreventLoader: 	at java.net.ServerSocket.<init>(ServerSocket.java:237)
02-23 10:22:10.857 12700 12709 D BreventLoader: 	at me.piebridge.brevent.server.BreventServer.main(BreventServer.java:849)
02-23 10:22:10.857 12700 12709 D BreventLoader: 	... 3 more
02-23 10:22:10.858 12700 12700 D BreventLoader: Brevent Server quit in 30 seconds, quit
--- brevent end ---
cannot listen port, please report bug to https://github.com/liudongmiao/Brevent/issues with log above
```

**Comment by liudongmiao** [comment]
su shell 也没有网络权限。

你可以运行 su shell id，贴下结果。

后续版本将支持 su 问题。

暂时的话，请先不要使用 su shell，直接运行 adb unroot 或者  adb usb 获取普通版本的 shell

**Comment by wangyou** [comment]
这是我的问题…我就不开新的了…这里贴一下吧
一加一…omni 7.1 02/19。
命令用的是/data/app/me.piebridge.brevent-1/lib/arm/libbootstrap.so
以下是终端运行情况…
手机上…附近没有电脑……
$/data/app/me.piebridge.brevent-1/lib/arm/libbootstrap.so
checking............cannot listen port
please report bug to https://github.com/liudongmiao/Brevent/issues with log below
--- crash start ---
02-24 03:47:28.774 12594 12594 F libc    : CANNOT LINK EXECUTABLE "/system/bin/app_process32": cannot locate symbol "XzUnpacker_Construct" referenced by "/system/lib/libunwind.so"...
02-24 03:47:28.774 12594 12594 F libc    : Fatal signal 6 (SIGABRT), code -6 in tid 12594 (app_process32)
02-24 03:47:28.802 12594 12594 F libc    : failed to resend signal during crash: Operation not permitted
--- crash end ---
--- brevent start ---
--- brevent end ---
cannot listen port, please report bug to https://github.com/liudongmiao/Brevent/issues with log above
$

**Comment by liudongmiao** [comment]
问下 ROM 提供商吧。。。

**Comment by liudongmiao** [comment]
十天内没有继续反馈，关闭。
