### ISSUE TITLE
在z9max miui8 安卓6.0上无法使用 - 无法获取最近列表

### ISSUE THREAD

**Issue by lelemka0** [liudongmiao/Brevent#131]
如题 已更新到0.7.4

PS C:\tools\adb> .\adb.exe -d shell
adb server is out of date.  killing...
* daemon started successfully *
shell@NX510J:/ $ /data/app/me.piebridge.brevent-2/lib/arm/libbootstrap.so
/data/app/me.piebridge.brevent-2/lib/arm/libbootstrap.so
```
checking...brevent_server started, pid: 19739
checking for stable..quited

please report bug to https://github.com/liudongmiao/Brevent/issues with log below
--- crash start ---
open /proc/kmsg failed: Permission denied
02-25 11:44:45.775 17157 17157 F libc    : page record for 0xf70b600c was not found (block_size=64)
02-25 11:44:45.821 17158 17158 F libc    : page record for 0xf70ca00c was not found (block_size=64)
02-25 11:44:46.635 17176 17176 F libc    : page record for 0xf76ba00c was not found (block_size=64)
02-25 11:44:46.807 17182 17182 F libc    : page record for 0xf716400c was not found (block_size=64)
02-25 12:16:56.198 26540 26540 F libc    : page record for 0xf70fe00c was not found (block_size=64)
02-25 12:16:56.215 26542 26542 F libc    : page record for 0xf705400c was not found (block_size=64)
02-25 12:16:56.228 26544 26544 F libc    : page record for 0xf752000c was not found (block_size=64)
02-25 12:16:56.776 26548 26548 F libc    : page record for 0xf72e200c was not found (block_size=64)
02-25 12:16:56.919 26551 26551 F libc    : page record for 0xf730600c was not found (block_size=64)
02-25 12:16:56.956 26554 26554 F libc    : page record for 0xf760e00c was not found (block_size=64)
02-25 12:18:34.531 27574 27574 F libc    : page record for 0xf757000c was not found (block_size=64)
02-25 12:18:34.546 27576 27576 F libc    : page record for 0xf771000c was not found (block_size=64)
02-25 12:18:34.561 27577 27577 F libc    : page record for 0xf77a200c was not found (block_size=64)
02-25 12:18:34.990 27581 27581 F libc    : page record for 0xf75a400c was not found (block_size=64)
02-25 12:18:35.020 27584 27584 F libc    : page record for 0xf75a800c was not found (block_size=64)
02-25 12:18:35.050 27587 27587 F libc    : page record for 0xf702000c was not found (block_size=64)
02-25 12:33:11.255 31498 31498 F libc    : page record for 0xf751200c was not found (block_size=64)
02-25 12:33:11.269 31500 31500 F libc    : page record for 0xf719e00c was not found (block_size=64)
02-25 12:33:11.284 31501 31501 F libc    : page record for 0xf706200c was not found (block_size=64)
02-25 12:33:11.677 31504 31504 F libc    : page record for 0xf71ca00c was not found (block_size=64)
02-25 12:33:11.721 31507 31507 F libc    : page record for 0xf730800c was not found (block_size=64)
02-25 14:34:26.279  2018  2018 F libc    : page record for 0xf732a00c was not found (block_size=64)
02-25 14:34:26.301  2022  2022 F libc    : page record for 0xf723e00c was not found (block_size=64)
02-25 14:34:26.315  2023  2023 F libc    : page record for 0xf713200c was not found (block_size=64)
02-25 14:34:26.576  2030  2030 F libc    : page record for 0xf73e800c was not found (block_size=64)
02-25 14:34:26.606  2034  2034 F libc    : page record for 0xf729a00c was not found (block_size=64)
02-25 14:34:26.641  2041  2041 F libc    : page record for 0xf767400c was not found (block_size=64)
02-25 14:35:27.892  4712  4712 F libc    : page record for 0xf70fa00c was not found (block_size=64)
02-25 14:35:27.913  4713  4713 F libc    : page record for 0xf72ec00c was not found (block_size=64)
02-25 14:35:27.927  4715  4715 F libc    : page record for 0xf6fb200c was not found (block_size=64)
02-25 14:35:28.273  4723  4723 F libc    : page record for 0xf753600c was not found (block_size=64)
02-25 14:35:28.434  4727  4727 F libc    : page record for 0xf76b600c was not found (block_size=64)
02-25 14:35:28.489  4730  4730 F libc    : page record for 0xf6fe200c was not found (block_size=64)
02-25 14:53:32.503 10333 10333 F libc    : page record for 0xf75b000c was not found (block_size=64)
02-25 14:53:32.938 10374 10374 F libc    : page record for 0xf72b000c was not found (block_size=64)
02-25 14:53:32.952 10375 10375 F libc    : page record for 0xf733000c was not found (block_size=64)
02-25 14:53:33.646 10425 10425 F libc    : page record for 0xf777a00c was not found (block_size=64)
02-25 14:53:33.733 10431 10431 F libc    : page record for 0xf718000c was not found (block_size=64)
02-25 16:29:16.269 12883 12883 F libc    : page record for 0xf70d200c was not found (block_size=64)
02-25 16:29:16.282 12885 12885 F libc    : page record for 0xf741200c was not found (block_size=64)
02-25 16:29:16.297 12886 12886 F libc    : page record for 0xf754400c was not found (block_size=64)
02-25 16:29:16.582 12890 12890 F libc    : page record for 0xf6fec00c was not found (block_size=64)
02-25 16:29:16.616 12893 12893 F libc    : page record for 0xf763c00c was not found (block_size=64)
02-25 16:29:16.643 12896 12896 F libc    : page record for 0xf6ffe00c was not found (block_size=64)
02-25 16:30:02.783 15238 15238 F libc    : page record for 0xf700c00c was not found (block_size=64)
02-25 16:30:02.818 15242 15242 F libc    : page record for 0xf73e400c was not found (block_size=64)
02-25 16:30:02.848 15246 15246 F libc    : page record for 0xf72bc00c was not found (block_size=64)
02-25 16:30:03.224 15263 15263 F libc    : page record for 0xf74f400c was not found (block_size=64)
02-25 16:30:03.572 15274 15274 F libc    : page record for 0xf712e00c was not found (block_size=64)
02-25 16:36:14.809 18836 18836 F libc    : page record for 0xf724600c was not found (block_size=64)
02-25 16:36:14.825 18839 18839 F libc    : page record for 0xf76d400c was not found (block_size=64)
02-25 16:36:14.840 18842 18842 F libc    : page record for 0xf748600c was not found (block_size=64)
02-25 16:36:15.214 18848 18848 F libc    : page record for 0xf76e800c was not found (block_size=64)
02-25 16:36:15.451 18866 18866 F libc    : page record for 0xf77a000c was not found (block_size=64)
02-25 16:36:15.489 18869 18869 F libc    : page record for 0xf71b600c was not found (block_size=64)
02-25 16:55:30.498 25815 25815 F libc    : page record for 0xf744a00c was not found (block_size=64)
02-25 16:55:30.512 25817 25817 F libc    : page record for 0xf74da00c was not found (block_size=64)
02-25 16:55:30.527 25819 25819 F libc    : page record for 0xf767c00c was not found (block_size=64)
02-25 16:55:30.879 25826 25826 F libc    : page record for 0xf71aa00c was not found (block_size=64)
02-25 16:55:31.174 25829 25829 F libc    : page record for 0xf70f600c was not found (block_size=64)
02-25 17:02:56.658 28151 28151 F libc    : page record for 0xf703e00c was not found (block_size=64)
02-25 17:02:56.941 28157 28157 F libc    : page record for 0xf74e400c was not found (block_size=64)
02-25 17:02:56.953 28158 28158 F libc    : page record for 0xf705e00c was not found (block_size=64)
02-25 17:02:57.804 28163 28163 F libc    : page record for 0xf766000c was not found (block_size=64)
02-25 17:03:01.602 28175 28175 F libc    : page record for 0xf752000c was not found (block_size=64)
02-25 17:05:31.045 29549 29549 F libc    : page record for 0xf742800c was not found (block_size=64)
02-25 17:05:31.060 29552 29552 F libc    : page record for 0xf72e200c was not found (block_size=64)
02-25 17:05:31.082 29553 29553 F libc    : page record for 0xf752400c was not found (block_size=64)
02-25 17:05:31.509 29558 29558 F libc    : page record for 0xf754000c was not found (block_size=64)
02-25 17:05:31.660 29567 29567 F libc    : page record for 0xf6fe600c was not found (block_size=64)
02-25 17:25:11.027   745   745 F libc    : page record for 0xf74a200c was not found (block_size=64)
02-25 17:25:11.213   752   752 F libc    : page record for 0xf754000c was not found (block_size=64)
02-25 17:25:11.270   754   754 F libc    : page record for 0xf713c00c was not found (block_size=64)
02-25 17:25:12.528   767   767 F libc    : page record for 0xf70d200c was not found (block_size=64)
02-25 17:25:13.535   783   783 F libc    : page record for 0xf779400c was not found (block_size=64)
02-25 17:26:03.279  2995  2995 F libc    : page record for 0xf77a000c was not found (block_size=64)
02-25 17:26:03.297  2998  2998 F libc    : page record for 0xf775000c was not found (block_size=64)
02-25 17:26:03.314  3000  3000 F libc    : page record for 0xf769a00c was not found (block_size=64)
02-25 17:26:03.918  3003  3003 F libc    : page record for 0xf71e800c was not found (block_size=64)
02-25 17:26:04.088  3007  3007 F libc    : page record for 0xf725000c was not found (block_size=64)
02-25 17:26:04.151  3013  3013 F libc    : page record for 0xf738e00c was not found (block_size=64)
02-25 18:08:22.027  8180  8180 F libc    : page record for 0xf74ee00c was not found (block_size=64)
02-25 18:08:22.041  8182  8182 F libc    : page record for 0xf71d000c was not found (block_size=64)
02-25 18:08:22.055  8183  8183 F libc    : page record for 0xf74f600c was not found (block_size=64)
02-25 18:08:22.462  8187  8187 F libc    : page record for 0xf70aa00c was not found (block_size=64)
02-25 18:08:22.566  8194  8194 F libc    : page record for 0xf71e000c was not found (block_size=64)
02-25 18:08:22.636  8198  8198 F libc    : page record for 0xf70e000c was not found (block_size=64)
02-25 18:12:35.728 11942 11942 F libc    : page record for 0xf704a00c was not found (block_size=64)
02-25 18:12:35.752 11944 11944 F libc    : page record for 0xf716800c was not found (block_size=64)
02-25 18:12:35.772 11946 11946 F libc    : page record for 0xf721200c was not found (block_size=64)
02-25 18:12:36.144 11957 11957 F libc    : page record for 0xf71b600c was not found (block_size=64)
02-25 18:12:36.370 11969 11969 F libc    : page record for 0xf70d400c was not found (block_size=64)
02-25 18:23:27.471 15358 15358 F libc    : page record for 0xf711200c was not found (block_size=64)
02-25 18:23:27.489 15360 15360 F libc    : page record for 0xf776400c was not found (block_size=64)
02-25 18:23:27.507 15361 15361 F libc    : page record for 0xf753400c was not found (block_size=64)
02-25 18:23:27.799 15366 15366 F libc    : page record for 0xf729c00c was not found (block_size=64)
02-25 18:23:27.955 15375 15375 F libc    : page record for 0xf702400c was not found (block_size=64)
02-25 18:23:27.985 15378 15378 F libc    : page record for 0xf713400c was not found (block_size=64)
02-25 18:27:10.603 19739 19752 E AndroidRuntime: *** FATAL EXCEPTION IN SYSTEM PROCESS: Thread-10
02-25 18:27:10.603 19739 19752 E AndroidRuntime: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
02-25 18:27:10.603 19739 19752 E AndroidRuntime:        at me.piebridge.brevent.loader.Brevent.run(Brevent.java:62)
02-25 18:27:10.603 19739 19752 E AndroidRuntime:        at java.lang.Thread.run(Thread.java:818)
02-25 18:27:10.603 19739 19752 E AndroidRuntime: Caused by: java.lang.reflect.InvocationTargetException
02-25 18:27:10.603 19739 19752 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
02-25 18:27:10.603 19739 19752 E AndroidRuntime:        at me.piebridge.brevent.loader.Brevent.run(Brevent.java:59)
02-25 18:27:10.603 19739 19752 E AndroidRuntime:        ... 1 more
02-25 18:27:10.603 19739 19752 E AndroidRuntime: Caused by: java.lang.IllegalArgumentException:  is not a constant in an
droid.text.Layout$Alignment
02-25 18:27:10.603 19739 19752 E AndroidRuntime:        at java.lang.Enum.valueOf(Enum.java:200)
02-25 18:27:10.603 19739 19752 E AndroidRuntime:        at android.text.Layout$Alignment.valueOf(Layout.java:2017)
02-25 18:27:10.603 19739 19752 E AndroidRuntime:        at android.text.style.AlignmentSpan$Standard.<init>(AlignmentSpa
n.java:33)
02-25 18:27:10.603 19739 19752 E AndroidRuntime:        at android.text.TextUtils$1.createFromParcel(TextUtils.java:711)
02-25 18:27:10.603 19739 19752 E AndroidRuntime:        at android.text.TextUtils$1.createFromParcel(TextUtils.java:684)
02-25 18:27:10.603 19739 19752 E AndroidRuntime:        at android.app.ActivityManager$RecentTaskInfo.readFromParcel(Act
ivityManager.java:944)
02-25 18:27:10.603 19739 19752 E AndroidRuntime:        at android.app.ActivityManager$RecentTaskInfo.<init>(ActivityMan
ager.java:969)
02-25 18:27:10.603 19739 19752 E AndroidRuntime:        at android.app.ActivityManager$RecentTaskInfo.<init>(ActivityMan
ager.java:810)
02-25 18:27:10.603 19739 19752 E AndroidRuntime:        at android.app.ActivityManager$RecentTaskInfo$1.createFromParcel
(ActivityManager.java:961)
02-25 18:27:10.603 19739 19752 E AndroidRuntime:        at android.app.ActivityManager$RecentTaskInfo$1.createFromParcel
(ActivityManager.java:959)
02-25 18:27:10.603 19739 19752 E AndroidRuntime:        at android.os.Parcel.createTypedArrayList(Parcel.java:2007)
02-25 18:27:10.603 19739 19752 E AndroidRuntime:        at android.app.ActivityManagerProxy.getRecentTasks(ActivityManag
erNative.java:3332)
02-25 18:27:10.603 19739 19752 E AndroidRuntime:        at me.piebridge.brevent.server.f.a(HideApiOverrideM.java:22)
02-25 18:27:10.603 19739 19752 E AndroidRuntime:        at me.piebridge.brevent.server.BreventServer.d(BreventServer.jav
a:347)
02-25 18:27:10.603 19739 19752 E AndroidRuntime:        at me.piebridge.brevent.server.BreventServer.c(BreventServer.jav
a:237)
02-25 18:27:10.603 19739 19752 E AndroidRuntime:        at me.piebridge.brevent.server.BreventServer.a(BreventServer.jav
a:739)
02-25 18:27:10.603 19739 19752 E AndroidRuntime:        at me.piebridge.brevent.server.BreventServer.<init>(BreventServe
r.java:140)
02-25 18:27:10.603 19739 19752 E AndroidRuntime:        at me.piebridge.brevent.server.BreventServer.main(BreventServer.
java:875)
02-25 18:27:10.603 19739 19752 E AndroidRuntime:        ... 3 more
02-25 18:27:10.608 19739 19752 E AndroidRuntime: Error reporting crash
02-25 18:27:10.608 19739 19752 E AndroidRuntime: java.lang.RuntimeException: Bad file descriptor
02-25 18:27:10.608 19739 19752 E AndroidRuntime:        at android.os.BinderProxy.transactNative(Native Method)
02-25 18:27:10.608 19739 19752 E AndroidRuntime:        at android.os.BinderProxy.transact(Binder.java:532)
02-25 18:27:10.608 19739 19752 E AndroidRuntime:        at android.app.ActivityManagerProxy.handleApplicationCrash(Activ
ityManagerNative.java:4466)
02-25 18:27:10.608 19739 19752 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$UncaughtHandler.uncaughtE
xception(RuntimeInit.java:90)
02-25 18:27:10.608 19739 19752 E AndroidRuntime:        at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:693)
02-25 18:27:10.608 19739 19752 E AndroidRuntime:        at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:690)
--- crash end ---
--- brevent start ---
open /proc/kmsg failed: Permission denied
02-25 18:27:10.313 19739 19739 D BreventLoader: lib: /data/user/0/com.android.shell/brevent, loader: /data/user/0/com.an
droid.shell/brevent/libloader.so
02-25 18:27:10.406 19739 19752 D BreventServer: Brevent Server 0.7.4 started
02-25 18:27:10.412 19739 19752 D BreventServer: brevent user: 0
02-25 18:27:10.415 19739 19752 D BreventServer: brevent data directory: /data/user/0/com.android.shell
02-25 18:27:10.529 19739 19752 D BreventServer: loaded brevent list
02-25 18:27:10.530 19739 19752 D BreventServer: loaded brevent conf
02-25 18:27:10.557 19739 19752 D BreventServer: checking
02-25 18:27:10.601 19739 19752 D BreventLoader: Can't run brevent server
02-25 18:27:10.601 19739 19752 D BreventLoader: java.lang.reflect.InvocationTargetException
02-25 18:27:10.601 19739 19752 D BreventLoader:         at java.lang.reflect.Method.invoke(Native Method)
02-25 18:27:10.601 19739 19752 D BreventLoader:         at me.piebridge.brevent.loader.Brevent.run(Brevent.java:59)
02-25 18:27:10.601 19739 19752 D BreventLoader:         at java.lang.Thread.run(Thread.java:818)
02-25 18:27:10.601 19739 19752 D BreventLoader: Caused by: java.lang.IllegalArgumentException:  is not a constant in and
roid.text.Layout$Alignment
02-25 18:27:10.601 19739 19752 D BreventLoader:         at java.lang.Enum.valueOf(Enum.java:200)
02-25 18:27:10.601 19739 19752 D BreventLoader:         at android.text.Layout$Alignment.valueOf(Layout.java:2017)
02-25 18:27:10.601 19739 19752 D BreventLoader:         at android.text.style.AlignmentSpan$Standard.<init>(AlignmentSpa
n.java:33)
02-25 18:27:10.601 19739 19752 D BreventLoader:         at android.text.TextUtils$1.createFromParcel(TextUtils.java:711)
02-25 18:27:10.601 19739 19752 D BreventLoader:         at android.text.TextUtils$1.createFromParcel(TextUtils.java:684)
02-25 18:27:10.601 19739 19752 D BreventLoader:         at android.app.ActivityManager$RecentTaskInfo.readFromParcel(Act
ivityManager.java:944)
02-25 18:27:10.601 19739 19752 D BreventLoader:         at android.app.ActivityManager$RecentTaskInfo.<init>(ActivityMan
ager.java:969)
02-25 18:27:10.601 19739 19752 D BreventLoader:         at android.app.ActivityManager$RecentTaskInfo.<init>(ActivityMan
ager.java:810)
02-25 18:27:10.601 19739 19752 D BreventLoader:         at android.app.ActivityManager$RecentTaskInfo$1.createFromParcel
(ActivityManager.java:961)
02-25 18:27:10.601 19739 19752 D BreventLoader:         at android.app.ActivityManager$RecentTaskInfo$1.createFromParcel
(ActivityManager.java:959)
02-25 18:27:10.601 19739 19752 D BreventLoader:         at android.os.Parcel.createTypedArrayList(Parcel.java:2007)
02-25 18:27:10.601 19739 19752 D BreventLoader:         at android.app.ActivityManagerProxy.getRecentTasks(ActivityManag
erNative.java:3332)
02-25 18:27:10.601 19739 19752 D BreventLoader:         at me.piebridge.brevent.server.f.a(HideApiOverrideM.java:22)
02-25 18:27:10.601 19739 19752 D BreventLoader:         at me.piebridge.brevent.server.BreventServer.d(BreventServer.jav
a:347)
02-25 18:27:10.601 19739 19752 D BreventLoader:         at me.piebridge.brevent.server.BreventServer.c(BreventServer.jav
a:237)
02-25 18:27:10.601 19739 19752 D BreventLoader:         at me.piebridge.brevent.server.BreventServer.a(BreventServer.jav
a:739)
02-25 18:27:10.601 19739 19752 D BreventLoader:         at me.piebridge.brevent.server.BreventServer.<init>(BreventServe
r.java:140)
02-25 18:27:10.601 19739 19752 D BreventLoader:         at me.piebridge.brevent.server.BreventServer.main(BreventServer.
java:875)
02-25 18:27:10.601 19739 19752 D BreventLoader:         ... 3 more
02-25 18:27:10.602 19739 19739 D BreventLoader: Brevent Server quit in 30 seconds, quit
--- brevent end ---
cannot listen port, please report bug to https://github.com/liudongmiao/Brevent/issues with log above
```

**Comment by liudongmiao** [comment]
请看下是否持续这样。如果一直这样的话，我就得考虑绕过了。

最近列表是一个检测什么时候强杀的判断依据，如果没有这个信息，可能只能一直强杀不休眠了。

**Comment by lelemka0** [comment]
一直都是这样的，之前的各个版本也是这样

**Comment by liudongmiao** [comment]
带上这个日志，找你的 ROM 提供商。

**Comment by lelemka0** [comment]
更新到0.8+9以后 错误日志不一样了

> shell@NX510J:/ $ /data/app/me.piebridge.brevent-2/lib/arm64/libbootstrap.so
/data/app/me.piebridge.brevent-2/lib/arm64/libbootstrap.so
checking...brevent_server started, pid: 25144
checking for stable..quited

please report bug to https://github.com/liudongmiao/Brevent/issues with log below
--- crash start ---
>>> logcat -b crash -t '03-03 22:49:15.000' -d
open /proc/kmsg failed: Permission denied
03-03 22:49:16.598 25144 25152 E AndroidRuntime: *** FATAL EXCEPTION IN SYSTEM PROCESS: Thread-10
03-03 22:49:16.598 25144 25152 E AndroidRuntime: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
03-03 22:49:16.598 25144 25152 E AndroidRuntime:        at me.piebridge.brevent.loader.Brevent.run(Brevent.java:63)
03-03 22:49:16.598 25144 25152 E AndroidRuntime:        at java.lang.Thread.run(Thread.java:818)
03-03 22:49:16.598 25144 25152 E AndroidRuntime: Caused by: java.lang.reflect.InvocationTargetException
03-03 22:49:16.598 25144 25152 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
03-03 22:49:16.598 25144 25152 E AndroidRuntime:        at me.piebridge.brevent.loader.Brevent.run(Brevent.java:60)
03-03 22:49:16.598 25144 25152 E AndroidRuntime:        ... 1 more
03-03 22:49:16.598 25144 25152 E AndroidRuntime: Caused by: java.lang.IllegalArgumentException:  is not a constant in an
droid.text.Layout$Alignment
03-03 22:49:16.598 25144 25152 E AndroidRuntime:        at java.lang.Enum.valueOf(Enum.java:200)
03-03 22:49:16.598 25144 25152 E AndroidRuntime:        at android.text.Layout$Alignment.valueOf(Layout.java:2017)
03-03 22:49:16.598 25144 25152 E AndroidRuntime:        at android.text.style.AlignmentSpan$Standard.<init>(AlignmentSpa
n.java:33)
03-03 22:49:16.598 25144 25152 E AndroidRuntime:        at android.text.TextUtils$1.createFromParcel(TextUtils.java:711)
03-03 22:49:16.598 25144 25152 E AndroidRuntime:        at android.text.TextUtils$1.createFromParcel(TextUtils.java:684)
03-03 22:49:16.598 25144 25152 E AndroidRuntime:        at android.app.ActivityManager$RecentTaskInfo.readFromParcel(Act
ivityManager.java:944)
03-03 22:49:16.598 25144 25152 E AndroidRuntime:        at android.app.ActivityManager$RecentTaskInfo.<init>(ActivityMan
ager.java:969)
03-03 22:49:16.598 25144 25152 E AndroidRuntime:        at android.app.ActivityManager$RecentTaskInfo.<init>(ActivityMan
ager.java:810)
03-03 22:49:16.598 25144 25152 E AndroidRuntime:        at android.app.ActivityManager$RecentTaskInfo$1.createFromParcel
(ActivityManager.java:961)
03-03 22:49:16.598 25144 25152 E AndroidRuntime:        at android.app.ActivityManager$RecentTaskInfo$1.createFromParcel
(ActivityManager.java:959)
03-03 22:49:16.598 25144 25152 E AndroidRuntime:        at android.os.Parcel.createTypedArrayList(Parcel.java:2007)
03-03 22:49:16.598 25144 25152 E AndroidRuntime:        at android.app.ActivityManagerProxy.getRecentTasks(ActivityManag
erNative.java:3332)
03-03 22:49:16.598 25144 25152 E AndroidRuntime:        at me.piebridge.brevent.server.f.a(HideApiOverrideM.java:22)
03-03 22:49:16.598 25144 25152 E AndroidRuntime:        at me.piebridge.brevent.server.BreventServer.e(BreventServer.jav
a:449)
03-03 22:49:16.598 25144 25152 E AndroidRuntime:        at me.piebridge.brevent.server.BreventServer.d(BreventServer.jav
a:273)
03-03 22:49:16.598 25144 25152 E AndroidRuntime:        at me.piebridge.brevent.server.BreventServer.a(BreventServer.jav
a:866)
03-03 22:49:16.598 25144 25152 E AndroidRuntime:        at me.piebridge.brevent.server.BreventServer.<init>(BreventServe
r.java:150)
03-03 22:49:16.598 25144 25152 E AndroidRuntime:        at me.piebridge.brevent.server.BreventServer.main(BreventServer.
java:1005)
03-03 22:49:16.598 25144 25152 E AndroidRuntime:        ... 3 more
03-03 22:49:16.609 25144 25152 E AndroidRuntime: Error reporting crash
03-03 22:49:16.609 25144 25152 E AndroidRuntime: java.lang.RuntimeException: Bad file descriptor
03-03 22:49:16.609 25144 25152 E AndroidRuntime:        at android.os.BinderProxy.transactNative(Native Method)
03-03 22:49:16.609 25144 25152 E AndroidRuntime:        at android.os.BinderProxy.transact(Binder.java:532)
03-03 22:49:16.609 25144 25152 E AndroidRuntime:        at android.app.ActivityManagerProxy.handleApplicationCrash(Activ
ityManagerNative.java:4466)
03-03 22:49:16.609 25144 25152 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$UncaughtHandler.uncaughtE
xception(RuntimeInit.java:90)
03-03 22:49:16.609 25144 25152 E AndroidRuntime:        at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:693)
03-03 22:49:16.609 25144 25152 E AndroidRuntime:        at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:690)
--- crash end ---
--- brevent start ---
>>> logcat -b main -t '03-03 22:49:15.000' -d -s BreventLoader BreventServer
open /proc/kmsg failed: Permission denied
03-03 22:49:16.099 25144 25144 I BreventLoader: lib: /data/user/0/com.android.shell/brevent, loader: /data/user/0/com.an
droid.shell/brevent/libloader.so
03-03 22:49:16.134 25144 25152 I BreventServer: Brevent Server 0.8-9-g9b44ee1 started
03-03 22:49:16.169 25144 25152 I BreventServer: brevent user: 0
03-03 22:49:16.172 25144 25152 I BreventServer: brevent data directory: /data/user/0/com.android.shell
03-03 22:49:16.502 25144 25152 I BreventServer: loading brevent list
03-03 22:49:16.504 25144 25152 I BreventServer: loading brevent conf
03-03 22:49:16.543 25144 25152 D BreventServer: check and brevent
03-03 22:49:16.597 25144 25152 W BreventLoader: Can't run brevent server
03-03 22:49:16.597 25144 25152 W BreventLoader: java.lang.reflect.InvocationTargetException
03-03 22:49:16.597 25144 25152 W BreventLoader:         at java.lang.reflect.Method.invoke(Native Method)
03-03 22:49:16.597 25144 25152 W BreventLoader:         at me.piebridge.brevent.loader.Brevent.run(Brevent.java:60)
03-03 22:49:16.597 25144 25152 W BreventLoader:         at java.lang.Thread.run(Thread.java:818)
03-03 22:49:16.597 25144 25152 W BreventLoader: Caused by: java.lang.IllegalArgumentException:  is not a constant in and
roid.text.Layout$Alignment
03-03 22:49:16.597 25144 25152 W BreventLoader:         at java.lang.Enum.valueOf(Enum.java:200)
03-03 22:49:16.597 25144 25152 W BreventLoader:         at android.text.Layout$Alignment.valueOf(Layout.java:2017)
03-03 22:49:16.597 25144 25152 W BreventLoader:         at android.text.style.AlignmentSpan$Standard.<init>(AlignmentSpa
n.java:33)
03-03 22:49:16.597 25144 25152 W BreventLoader:         at android.text.TextUtils$1.createFromParcel(TextUtils.java:711)
03-03 22:49:16.597 25144 25152 W BreventLoader:         at android.text.TextUtils$1.createFromParcel(TextUtils.java:684)
03-03 22:49:16.597 25144 25152 W BreventLoader:         at android.app.ActivityManager$RecentTaskInfo.readFromParcel(Act
ivityManager.java:944)
03-03 22:49:16.597 25144 25152 W BreventLoader:         at android.app.ActivityManager$RecentTaskInfo.<init>(ActivityMan
ager.java:969)
03-03 22:49:16.597 25144 25152 W BreventLoader:         at android.app.ActivityManager$RecentTaskInfo.<init>(ActivityMan
ager.java:810)
03-03 22:49:16.597 25144 25152 W BreventLoader:         at android.app.ActivityManager$RecentTaskInfo$1.createFromParcel
(ActivityManager.java:961)
03-03 22:49:16.597 25144 25152 W BreventLoader:         at android.app.ActivityManager$RecentTaskInfo$1.createFromParcel
(ActivityManager.java:959)
03-03 22:49:16.597 25144 25152 W BreventLoader:         at android.os.Parcel.createTypedArrayList(Parcel.java:2007)
03-03 22:49:16.597 25144 25152 W BreventLoader:         at android.app.ActivityManagerProxy.getRecentTasks(ActivityManag
erNative.java:3332)
03-03 22:49:16.597 25144 25152 W BreventLoader:         at me.piebridge.brevent.server.f.a(HideApiOverrideM.java:22)
03-03 22:49:16.597 25144 25152 W BreventLoader:         at me.piebridge.brevent.server.BreventServer.e(BreventServer.jav
a:449)
03-03 22:49:16.597 25144 25152 W BreventLoader:         at me.piebridge.brevent.server.BreventServer.d(BreventServer.jav
a:273)
03-03 22:49:16.597 25144 25152 W BreventLoader:         at me.piebridge.brevent.server.BreventServer.a(BreventServer.jav
a:866)
03-03 22:49:16.597 25144 25152 W BreventLoader:         at me.piebridge.brevent.server.BreventServer.<init>(BreventServe
r.java:150)
03-03 22:49:16.597 25144 25152 W BreventLoader:         at me.piebridge.brevent.server.BreventServer.main(BreventServer.
java:1005)
03-03 22:49:16.597 25144 25152 W BreventLoader:         ... 3 more
03-03 22:49:16.599 25144 25144 E BreventLoader: Brevent Server quit in 30 seconds, quit
--- brevent end ---
cannot listen port, please report bug to https://github.com/liudongmiao/Brevent/issues with log above

**Comment by liudongmiao** [comment]
这个新异常，无法读取最近列表。

我会考虑下，没有这个的影响。总的来说，没有这个的话，无法知道应该什么时候退出。
当然，也有其它的手段可以获取这个东西，但我目前还没想好使用。

**Comment by liudongmiao** [comment]
十天内没有继续反馈，关闭。

**Comment by lelemka0** [comment]
0.8.7 还是一样的日志

**Comment by liudongmiao** [comment]
这个我不打算支持，无法获取最近任务列表。
