### ISSUE TITLE
Nexus 6p 7.1.2 没有权限写入 /data/user_de/0/com.android.shell/brevent/libreader.so (Permission denied)

### ISSUE THREAD

**Issue by Bob021** [liudongmiao/Brevent#132]
D:\angler\platform-tools-latest-windows\platform-tools>adb -d shell
a/app/me.piebridge.brevent-$x/lib/*/libbootstrap.so;if ls $file>/dev/null 2>&1;then $file;break;fi;done    
```                                                <
checking............cannot listen port
please report bug to https://github.com/liudongmiao/Brevent/issues with log below
--- crash start ---
02-25 13:29:49.788  9500  9500 E AndroidRuntime: *** FATAL EXCEPTION IN SYSTEM PROCESS: main
02-25 13:29:49.788  9500  9500 E AndroidRuntime: java.io.FileNotFoundException: /data/user_de/0/com.android.shell/brevent/libreader.so (Permission denied)
02-25 13:29:49.788  9500  9500 E AndroidRuntime:        at java.io.FileOutputStream.open(Native Method)
02-25 13:29:49.788  9500  9500 E AndroidRuntime:        at java.io.FileOutputStream.<init>(FileOutputStream.java:221)
02-25 13:29:49.788  9500  9500 E AndroidRuntime:        at java.io.FileOutputStream.<init>(FileOutputStream.java:169)
02-25 13:29:49.788  9500  9500 E AndroidRuntime:        at me.piebridge.brevent.loader.Brevent.a(Brevent.java:94)
02-25 13:29:49.788  9500  9500 E AndroidRuntime:        at me.piebridge.brevent.loader.Brevent.main(Brevent.java:109)
02-25 13:29:49.788  9500  9500 E AndroidRuntime:        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
02-25 13:29:49.788  9500  9500 E AndroidRuntime:        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:262)
02-25 13:29:49.797  9500  9500 E AndroidRuntime: Error reporting crash
02-25 13:29:49.797  9500  9500 E AndroidRuntime: java.lang.RuntimeException: Bad file descriptor
02-25 13:29:49.797  9500  9500 E AndroidRuntime:        at android.os.BinderProxy.transactNative(Native Method)
02-25 13:29:49.797  9500  9500 E AndroidRuntime:        at android.os.BinderProxy.transact(Binder.java:615)
02-25 13:29:49.797  9500  9500 E AndroidRuntime:        at android.os.ServiceManagerProxy.getService(ServiceManagerNative.java:123)
02-25 13:29:49.797  9500  9500 E AndroidRuntime:        at android.os.ServiceManager.getService(ServiceManager.java:55)
02-25 13:29:49.797  9500  9500 E AndroidRuntime:        at android.app.ActivityManagerNative$1.create(ActivityManagerNative.java:3049)
02-25 13:29:49.797  9500  9500 E AndroidRuntime:        at android.app.ActivityManagerNative$1.create(ActivityManagerNative.java:3048)
02-25 13:29:49.797  9500  9500 E AndroidRuntime:        at android.util.Singleton.get(Singleton.java:34)
02-25 13:29:49.797  9500  9500 E AndroidRuntime:        at android.app.ActivityManagerNative.getDefault(ActivityManagerNative.java:86)
02-25 13:29:49.797  9500  9500 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$UncaughtHandler.uncaughtException(RuntimeInit.java:97)
02-25 13:29:49.797  9500  9500 E AndroidRuntime:        at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1068)
02-25 13:29:49.797  9500  9500 E AndroidRuntime:        at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1063)
02-25 13:36:48.018 10242 10242 E AndroidRuntime: *** FATAL EXCEPTION IN SYSTEM PROCESS: main
02-25 13:36:48.018 10242 10242 E AndroidRuntime: java.io.FileNotFoundException: /data/user_de/0/com.android.shell/brevent/libreader.so (Permission denied)
02-25 13:36:48.018 10242 10242 E AndroidRuntime:        at java.io.FileOutputStream.open(Native Method)
02-25 13:36:48.018 10242 10242 E AndroidRuntime:        at java.io.FileOutputStream.<init>(FileOutputStream.java:221)
02-25 13:36:48.018 10242 10242 E AndroidRuntime:        at java.io.FileOutputStream.<init>(FileOutputStream.java:169)
02-25 13:36:48.018 10242 10242 E AndroidRuntime:        at me.piebridge.brevent.loader.Brevent.a(Brevent.java:94)
02-25 13:36:48.018 10242 10242 E AndroidRuntime:        at me.piebridge.brevent.loader.Brevent.main(Brevent.java:109)
02-25 13:36:48.018 10242 10242 E AndroidRuntime:        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
02-25 13:36:48.018 10242 10242 E AndroidRuntime:        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:262)
02-25 13:36:48.021 10242 10242 E AndroidRuntime: Error reporting crash
02-25 13:36:48.021 10242 10242 E AndroidRuntime: java.lang.RuntimeException: Bad file descriptor
02-25 13:36:48.021 10242 10242 E AndroidRuntime:        at android.os.BinderProxy.transactNative(Native Method)
02-25 13:36:48.021 10242 10242 E AndroidRuntime:        at android.os.BinderProxy.transact(Binder.java:615)
02-25 13:36:48.021 10242 10242 E AndroidRuntime:        at android.os.ServiceManagerProxy.getService(ServiceManagerNative.java:123)
02-25 13:36:48.021 10242 10242 E AndroidRuntime:        at android.os.ServiceManager.getService(ServiceManager.java:55)
02-25 13:36:48.021 10242 10242 E AndroidRuntime:        at android.app.ActivityManagerNative$1.create(ActivityManagerNative.java:3049)
02-25 13:36:48.021 10242 10242 E AndroidRuntime:        at android.app.ActivityManagerNative$1.create(ActivityManagerNative.java:3048)
02-25 13:36:48.021 10242 10242 E AndroidRuntime:        at android.util.Singleton.get(Singleton.java:34)
02-25 13:36:48.021 10242 10242 E AndroidRuntime:        at android.app.ActivityManagerNative.getDefault(ActivityManagerNative.java:86)
02-25 13:36:48.021 10242 10242 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$UncaughtHandler.uncaughtException(RuntimeInit.java:97)
02-25 13:36:48.021 10242 10242 E AndroidRuntime:        at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1068)
02-25 13:36:48.021 10242 10242 E AndroidRuntime:        at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1063)
02-25 13:38:43.188 10387 10387 E AndroidRuntime: *** FATAL EXCEPTION IN SYSTEM PROCESS: main
02-25 13:38:43.188 10387 10387 E AndroidRuntime: java.io.FileNotFoundException: /data/user_de/0/com.android.shell/brevent/libreader.so (Permission denied)
02-25 13:38:43.188 10387 10387 E AndroidRuntime:        at java.io.FileOutputStream.open(Native Method)
02-25 13:38:43.188 10387 10387 E AndroidRuntime:        at java.io.FileOutputStream.<init>(FileOutputStream.java:221)
02-25 13:38:43.188 10387 10387 E AndroidRuntime:        at java.io.FileOutputStream.<init>(FileOutputStream.java:169)
02-25 13:38:43.188 10387 10387 E AndroidRuntime:        at me.piebridge.brevent.loader.Brevent.a(Brevent.java:94)
02-25 13:38:43.188 10387 10387 E AndroidRuntime:        at me.piebridge.brevent.loader.Brevent.main(Brevent.java:109)
02-25 13:38:43.188 10387 10387 E AndroidRuntime:        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
02-25 13:38:43.188 10387 10387 E AndroidRuntime:        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:262)
02-25 13:38:43.189 10387 10387 E AndroidRuntime: Error reporting crash
02-25 13:38:43.189 10387 10387 E AndroidRuntime: java.lang.RuntimeException: Bad file descriptor
02-25 13:38:43.189 10387 10387 E AndroidRuntime:        at android.os.BinderProxy.transactNative(Native Method)
02-25 13:38:43.189 10387 10387 E AndroidRuntime:        at android.os.BinderProxy.transact(Binder.java:615)
02-25 13:38:43.189 10387 10387 E AndroidRuntime:        at android.os.ServiceManagerProxy.getService(ServiceManagerNative.java:123)
02-25 13:38:43.189 10387 10387 E AndroidRuntime:        at android.os.ServiceManager.getService(ServiceManager.java:55)
02-25 13:38:43.189 10387 10387 E AndroidRuntime:        at android.app.ActivityManagerNative$1.create(ActivityManagerNative.java:3049)
02-25 13:38:43.189 10387 10387 E AndroidRuntime:        at android.app.ActivityManagerNative$1.create(ActivityManagerNative.java:3048)
02-25 13:38:43.189 10387 10387 E AndroidRuntime:        at android.util.Singleton.get(Singleton.java:34)
02-25 13:38:43.189 10387 10387 E AndroidRuntime:        at android.app.ActivityManagerNative.getDefault(ActivityManagerNative.java:86)
02-25 13:38:43.189 10387 10387 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$UncaughtHandler.uncaughtException(RuntimeInit.java:97)
02-25 13:38:43.189 10387 10387 E AndroidRuntime:        at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1068)
02-25 13:38:43.189 10387 10387 E AndroidRuntime:        at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1063)
02-25 13:44:20.738 11537 11537 E AndroidRuntime: *** FATAL EXCEPTION IN SYSTEM PROCESS: main
02-25 13:44:20.738 11537 11537 E AndroidRuntime: java.io.FileNotFoundException: /data/user_de/0/com.android.shell/brevent/libreader.so (Permission denied)
02-25 13:44:20.738 11537 11537 E AndroidRuntime:        at java.io.FileOutputStream.open(Native Method)
02-25 13:44:20.738 11537 11537 E AndroidRuntime:        at java.io.FileOutputStream.<init>(FileOutputStream.java:221)
02-25 13:44:20.738 11537 11537 E AndroidRuntime:        at java.io.FileOutputStream.<init>(FileOutputStream.java:169)
02-25 13:44:20.738 11537 11537 E AndroidRuntime:        at me.piebridge.brevent.loader.Brevent.a(Brevent.java:94)
02-25 13:44:20.738 11537 11537 E AndroidRuntime:        at me.piebridge.brevent.loader.Brevent.main(Brevent.java:109)
02-25 13:44:20.738 11537 11537 E AndroidRuntime:        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
02-25 13:44:20.738 11537 11537 E AndroidRuntime:        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:262)
02-25 13:44:20.744 11537 11537 E AndroidRuntime: Error reporting crash
02-25 13:44:20.744 11537 11537 E AndroidRuntime: java.lang.RuntimeException: Bad file descriptor
02-25 13:44:20.744 11537 11537 E AndroidRuntime:        at android.os.BinderProxy.transactNative(Native Method)
02-25 13:44:20.744 11537 11537 E AndroidRuntime:        at android.os.BinderProxy.transact(Binder.java:615)
02-25 13:44:20.744 11537 11537 E AndroidRuntime:        at android.os.ServiceManagerProxy.getService(ServiceManagerNative.java:123)
02-25 13:44:20.744 11537 11537 E AndroidRuntime:        at android.os.ServiceManager.getService(ServiceManager.java:55)
02-25 13:44:20.744 11537 11537 E AndroidRuntime:        at android.app.ActivityManagerNative$1.create(ActivityManagerNative.java:3049)
02-25 13:44:20.744 11537 11537 E AndroidRuntime:        at android.app.ActivityManagerNative$1.create(ActivityManagerNative.java:3048)
02-25 13:44:20.744 11537 11537 E AndroidRuntime:        at android.util.Singleton.get(Singleton.java:34)
02-25 13:44:20.744 11537 11537 E AndroidRuntime:        at android.app.ActivityManagerNative.getDefault(ActivityManagerNative.java:86)
02-25 13:44:20.744 11537 11537 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$UncaughtHandler.uncaughtException(RuntimeInit.java:97)
02-25 13:44:20.744 11537 11537 E AndroidRuntime:        at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1068)
02-25 13:44:20.744 11537 11537 E AndroidRuntime:        at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1063)
02-25 13:46:55.480 12749 12749 E AndroidRuntime: *** FATAL EXCEPTION IN SYSTEM PROCESS: main
02-25 13:46:55.480 12749 12749 E AndroidRuntime: java.io.FileNotFoundException: /data/user_de/0/com.android.shell/brevent/libreader.so (Permission denied)
02-25 13:46:55.480 12749 12749 E AndroidRuntime:        at java.io.FileOutputStream.open(Native Method)
02-25 13:46:55.480 12749 12749 E AndroidRuntime:        at java.io.FileOutputStream.<init>(FileOutputStream.java:221)
02-25 13:46:55.480 12749 12749 E AndroidRuntime:        at java.io.FileOutputStream.<init>(FileOutputStream.java:169)
02-25 13:46:55.480 12749 12749 E AndroidRuntime:        at me.piebridge.brevent.loader.Brevent.a(Brevent.java:94)
02-25 13:46:55.480 12749 12749 E AndroidRuntime:        at me.piebridge.brevent.loader.Brevent.main(Brevent.java:109)
02-25 13:46:55.480 12749 12749 E AndroidRuntime:        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
02-25 13:46:55.480 12749 12749 E AndroidRuntime:        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:262)
02-25 13:46:55.480 12749 12749 E AndroidRuntime: Error reporting crash
02-25 13:46:55.480 12749 12749 E AndroidRuntime: java.lang.RuntimeException: Bad file descriptor
02-25 13:46:55.480 12749 12749 E AndroidRuntime:        at android.os.BinderProxy.transactNative(Native Method)
02-25 13:46:55.480 12749 12749 E AndroidRuntime:        at android.os.BinderProxy.transact(Binder.java:615)
02-25 13:46:55.480 12749 12749 E AndroidRuntime:        at android.os.ServiceManagerProxy.getService(ServiceManagerNative.java:123)
02-25 13:46:55.480 12749 12749 E AndroidRuntime:        at android.os.ServiceManager.getService(ServiceManager.java:55)
02-25 13:46:55.480 12749 12749 E AndroidRuntime:        at android.app.ActivityManagerNative$1.create(ActivityManagerNative.java:3049)
02-25 13:46:55.480 12749 12749 E AndroidRuntime:        at android.app.ActivityManagerNative$1.create(ActivityManagerNative.java:3048)
02-25 13:46:55.480 12749 12749 E AndroidRuntime:        at android.util.Singleton.get(Singleton.java:34)
02-25 13:46:55.480 12749 12749 E AndroidRuntime:        at android.app.ActivityManagerNative.getDefault(ActivityManagerNative.java:86)
02-25 13:46:55.480 12749 12749 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$UncaughtHandler.uncaughtException(RuntimeInit.java:97)
02-25 13:46:55.480 12749 12749 E AndroidRuntime:        at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1068)
02-25 13:46:55.480 12749 12749 E AndroidRuntime:        at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1063)
--- crash end ---
--- brevent start ---
--- brevent end ---
cannot listen port, please report bug to https://github.com/liudongmiao/Brevent/issues with log above
```

**Comment by liudongmiao** [comment]
> /data/user_de/0/com.android.shell/brevent/libreader.so (Permission denied)

看来，我需要认真考虑下，配置文件到底放在哪。暂没有打算支持 7.1.2 beta，因为我只有一款机器。等模拟器出来以后，会考虑下兼容性。

**Comment by Bob021** [comment]
OK,谢谢柳大。已经切回7.1.1系统，完美运行Play版黑域。再次感谢。

**Comment by liudongmiao** [comment]
也不要直接关闭这个问题啊。7.1.2 我也要测试呢～

**Comment by Bob021** [comment]
Sorry，，🤣

**Comment by Bob021** [comment]
最新版黑域，7.1.2原生系统可以用了，谢谢柳大。

**Comment by liudongmiao** [comment]
@Bob021 不太可能吧。是 root 了还是怎么样？

**Comment by Bob021** [comment]
没有Root, 普通ADB，现在用着挺好的

**Comment by liudongmiao** [comment]
我几乎没有改动什么。。。不过能用，就很好。

**Comment by Bob021** [comment]
具体原因我也不知道，我之前问过您，我更新到7.1.2后，黑域不能用，后来退回7.1.1，拿起手机唤醒屏幕不功能失效，后来我就重新更新7.1.2，尝试用新版黑域就可以了。
