### ISSUE TITLE
adb开启失败 - 无法获取默认的 PackageManager

### ISSUE THREAD

**Issue by 849506054** [liudongmiao/Brevent#134]
```
checking............cannot listen port
please report bug to https://github.com/liudongmiao/Brevent/issues with log below
--- crash start ---
02-25 17:10:37.168 15473 15469 F google-breakpad: M F5F2E000 00000000 00061000 38E3D0B624D3C2986644FDACC19B7BD70 libft2.so
02-25 17:10:37.168 15473 15469 F google-breakpad: M F5F92000 00000000 00025000 0C628443D69DC97795D20EC40EFB81320 libpng.so
02-25 17:10:37.168 15473 15469 F google-breakpad: M F5FB9000 00000000 00003000 0F78D3DEFD045C54625A923EBD81ACFA0 libsync.so
02-25 17:10:37.168 15473 15469 F google-breakpad: M F5FBE000 00000000 00005000 1B3BF18D74102E8F5C038A790C6C812C0 libstdc++.so
02-25 17:10:37.168 15473 15469 F google-breakpad: M F5FC5000 00000000 00010000 19C9664AA4D0A1E00EDB8A9CBF70DD2C0 libunwind.so
02-25 17:10:37.168 15473 15469 F google-breakpad: M F601D000 00000000 00009000 232625E025F3FF40376DD5AB33C5F1E10 libbase.so
02-25 17:10:37.168 15473 15469 F google-breakpad: M F6028000 00000000 00012000 71BDE3C6704F613A312A5B427F025D860 libpcre.so
02-25 17:10:37.168 15473 15469 F google-breakpad: M F603D000 00000000 00004000 12D04EB7E3BA8D72FE33F56E9CD8BFF90 libregionalization.so
02-25 17:10:37.168 15473 15469 F google-breakpad: M F6041000 00000000 00069000 0842D6DFFE88F7567BD30A5FDE7563BE0 libhwui.so
02-25 17:10:37.168 15473 15469 F google-breakpad: M F60AF000 00000000 00004000 3427CC929D523A78E1AD868E3BE56B200 liboem_jni.so
02-25 17:10:37.168 15473 15469 F google-breakpad: M F60B5000 00000000 00007000 D5DB97BE29F423F7FEF0FD59E60351CB0 libassert_tip_service.so
02-25 17:10:37.168 15473 15469 F google-breakpad: M F60BE000 00000000 00003000 47F3D7CD48E7831078ECC637C4C8ED6E0 libradio_metadata.so
02-25 17:10:37.168 15473 15469 F google-breakpad: M F60C3000 00000000 00004000 3025E74413D156DA5A099138D83921470 libnativebridge.so
02-25 17:10:37.168 15473 15469 F google-breakpad: M F60C9000 00000000 00004000 A567FBDEC8ACCE550ACDE760ACB87D470 libprocessgroup.so
02-25 17:10:37.169 15473 15469 F google-breakpad: M F60CF000 00000000 0000E000 3BD2953DF7A1F5236886DF458E1659860 libminikin.so
02-25 17:10:37.169 15473 15469 F google-breakpad: M F60DF000 00000000 0000B000 B9969085E7F9E14D2AA3C9C7CB5444A00 libsoundtrigger.so
02-25 17:10:37.169 15473 15469 F google-breakpad: M F60EE000 00000000 0000B000 BE260E2BDFA89D45DACD423661E8B0AF0 libradio.so
02-25 17:10:37.169 15473 15469 F google-breakpad: M F60FD000 00000000 00004000 7231D76CD86B56AFD3C25A002FDB99050 libnetd_client.so
02-25 17:10:37.169 15473 15469 F google-breakpad: M F6103000 00000000 0000D000 D9B9CE746CE85825615F6FD773DE248C0 libimg_utils.so
02-25 17:10:37.169 15473 15469 F google-breakpad: M F610D000 00000000 00404000 D34B8CA7B84E19BC2FC9ED7BBFB75D4B0 libpdfium.so
02-25 17:10:37.169 15473 15469 F google-breakpad: M F6520000 00000000 00007000 10D213A9B58BE4A6EF90EB92155CC2330 libaudioutils.so
02-25 17:10:37.169 15473 15469 F google-breakpad: M F6529000 00000000 0001A000 08D8D89C5808FAF4103DB7F9F838E8AE0 libz.so
02-25 17:10:37.169 15473 15469 F google-breakpad: M F6546000 00000000 00049000 62757EED551566B933375F4AA7CEBDA60 libharfbuzz_ng.so
02-25 17:10:37.169 15473 15469 F google-breakpad: M F6592000 00000000 00005000 B295925DE1176064E93C4BF46A8DBA5F0 libusbhost.so
02-25 17:10:37.169 15473 15469 F google-breakpad: M F6599000 00000000 00035000 AA5D4ECA79A8F21896ECB1271DB7A80C0 libjpeg.so
02-25 17:10:37.169 15473 15469 F google-breakpad: M F65BA000 00000000 000AA000 3BFBAB8BA46C60ECCC62C34E7F6447120 libmedia.so
02-25 17:10:37.169 15473 15469 F google-breakpad: M F667A000 00000000 0016C000 4ECA1FB61CC40971982064C38E57DDB00 libicui18n.so
02-25 17:10:37.169 15473 15469 F google-breakpad: M F67EC000 00000000 00116000 ECE783DB2CC2CD5091E0557A51C412050 libicuuc.so
02-25 17:10:37.169 15473 15469 F google-breakpad: M F6912000 00000000 00023000 9A99391225CF1034FD3127D08AE9F5B90 libssl.so
02-25 17:10:37.169 15473 15469 F google-breakpad: M F6938000 00000000 00090000 2C0B1E470153A81FA7322F2DD6BB91650 libcrypto.so
02-25 17:10:37.169 15473 15469 F google-breakpad: M F69D5000 00000000 00052000 48E3A0B63CF56C7A93CA326389F95BDB0 libsonivox.so
02-25 17:10:37.170 15473 15469 F google-breakpad: M F6A2F000 00000000 00008000 C3723CE152FB6F1C4DF559EFFD7A4C940 libhardware_legacy.so
02-25 17:10:37.170 15473 15469 F google-breakpad: M F6A3B000 00000000 00003000 51E13C6B3D9B3E798C9AA0952A55E3AE0 libhardware.so
02-25 17:10:37.170 15473 15469 F google-breakpad: M F6A40000 00000000 00004000 4E81F93A4CA22DE0FE521ECFC1B14AA60 libETC1.so
02-25 17:10:37.170 15473 15469 F google-breakpad: M F6A46000 00000000 0000D000 5F1A0577673558B08AD9BBA89A4BF9530 libGLESv2.so
02-25 17:10:37.170 15473 15469 F google-breakpad: M F6A55000 00000000 00008000 D441CE809396A15CBC6D1B999EB393AE0 libGLESv1_CM.so
02-25 17:10:37.170 15473 15469 F google-breakpad: M F6A57000 00000000 00064000 1E5333E5ADA6D0B4AD89BE4971E86D4C0 libEGL.so
02-25 17:10:37.170 15473 15469 F google-breakpad: M F6AC9000 00000000 00064000 6570678321D6D7C8F129433128290F080 libsqlite.so
02-25 17:10:37.170 15473 15469 F google-breakpad: M F6B1F000 00000000 0026C000 2DEBF193F03F5579FDC85CE253CCFFFE0 libskia.so
02-25 17:10:37.170 15473 15469 F google-breakpad: M F6DAD000 00000000 00008000 52E748D2C284F8DDA3B1A615CC9AB5530 libcamera_metadata.so
02-25 17:10:37.170 15473 15469 F google-breakpad: M F6DB4000 00000000 00028000 A1BA9E4CDD42D3F9EFC3F197478C313F0 libcamera_client.so
02-25 17:10:37.170 15473 15469 F google-breakpad: M F6DE4000 00000000 0003D000 7E1526A46891670CB1FAC5490387F3950 libinputflinger.so
02-25 17:10:37.170 15473 15469 F google-breakpad: M F6E23000 00000000 0001C000 A52BF64EF0F4EB7738BCAD129699AA9B0 libinput.so
02-25 17:10:37.170 15473 15469 F google-breakpad: M F6E3B000 00000000 00056000 49F02016974360CFE16A952361CC266D0 libgui.so
02-25 17:10:37.170 15473 15469 F google-breakpad: M F6E9E000 00000000 0000D000 07B1F6C005D3C150A2C483A3281C24230 libui.so
02-25 17:10:37.170 15473 15469 F google-breakpad: M F6EAE000 00000000 00007000 C0989C5D4D0C6242599547C1C49464B90 libnetutils.so
02-25 17:10:37.170 15473 15469 F google-breakpad: M F6EB7000 00000000 00007000 33F544B640C530BB4EA2B95619D5F63E0 libnativehelper.so
02-25 17:10:37.170 15473 15469 F google-breakpad: M F6EC0000 00000000 00014000 4350E54D4B7695CBB917EBE62906206B0 libexpat.so
02-25 17:10:37.170 15473 15469 F google-breakpad: M F6ED7000 00000000 00027000 2C726417CFB5914D3E94403745D48FC00 libandroidfw.so
02-25 17:10:37.171 15473 15469 F google-breakpad: M F6F01000 00000000 00003000 EA0DB6506209AC16A2EEBEA8F7ACD9660 libmemtrack.so
02-25 17:10:37.171 15473 15469 F google-breakpad: M F6F06000 00000000 00009000 3E2B50859B1B35FF2FE5C91071E334BC0 libbacktrace.so
02-25 17:10:37.171 15473 15469 F google-breakpad: M F6F11000 00000000 0001F000 6E3EAA54CFDBBB56097648CAB6D5919C0 libm.so
02-25 17:10:37.171 15473 15469 F google-breakpad: M F6F33000 00000000 00072000 959DFFE174BAE3166FA21E0709377E350 libc.so
02-25 17:10:37.171 15473 15469 F google-breakpad: M F6FB4000 00000000 0008B000 285AC6F8167FF8A0CF4FF79E658739140 libc++.so
02-25 17:10:37.171 15473 15469 F google-breakpad: M F7045000 00000000 0000F000 B94EF8F1E0AE71C80C9016B31648EB7E0 libselinux.so
02-25 17:10:37.171 15473 15469 F google-breakpad: M F7047000 00000000 000E1000 A1DD2FA1558256709754B4BBAA24F2170 libandroid_runtime.so
02-25 17:10:37.171 15473 15469 F google-breakpad: M F7134000 00000000 0002A000 F53ECB6C468F5D55BB7931C02E3A981D0 libbinder.so
02-25 17:10:37.171 15473 15469 F google-breakpad: M F7166000 00000000 00008000 722B992A99D7711466EB7E745D6923680 liblog.so
02-25 17:10:37.171 15473 15469 F google-breakpad: M F7170000 00000000 00018000 E41DC969651517E8BDAD4EF540B23A750 libutils.so
02-25 17:10:37.171 15473 15469 F google-breakpad: M F718B000 00000000 0000F000 FF53598DBA8F4799AEDF89D3ADB4A6800 libcutils.so
02-25 17:10:37.171 15473 15469 F google-breakpad: M F719D000 00000000 00004000 6000958350BC531E0B3B24D53C87906B0 libNimsWrap.so
02-25 17:10:37.171 15473 15469 F google-breakpad: M F71D4000 00000000 0001C000 7E84A26D70D2D4047A8E78F6C8FE36A30 linker
02-25 17:10:37.171 15473 15469 F google-breakpad: -----END BREAKPAD MICRODUMP-----
02-25 17:10:37.206 15120 15469 F libc    : Fatal signal 8 (SIGFPE), code -6, fault addr 0x3b10 in tid 15469 (RxComputationSc)
02-25 17:10:37.277   848   848 F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
02-25 17:10:37.278   848   848 F DEBUG   : Build fingerprint: 'OnePlus/OnePlus3/OnePlus3:6.0.1/MXB48T/361013:user/release-keys'
02-25 17:10:37.278   848   848 F DEBUG   : Revision: '0'
02-25 17:10:37.279   848   848 F DEBUG   : ABI: 'arm'
02-25 17:10:37.279   848   848 F DEBUG   : pid: 15120, tid: 15469, name: RxComputationSc  >>> me.ele <<<
02-25 17:10:37.279   848   848 F DEBUG   : signal 8 (SIGFPE), code -6 (SI_TKILL), fault addr 0x3b10
02-25 17:10:37.351   848   848 F DEBUG   :     r0 00000000  r1 00003c6d  r2 00000008  r3 d27e1978
02-25 17:10:37.351   848   848 F DEBUG   :     r4 d27e1980  r5 d27e1930  r6 00000002  r7 0000010c
02-25 17:10:37.351   848   848 F DEBUG   :     r8 00000000  r9 caa02578  sl 00000002  fp 00000000
02-25 17:10:37.351   848   848 F DEBUG   :     ip 00000008  sp d27e1338  lr f6f73145  pc f6f75540  cpsr 400b0010
02-25 17:10:37.363   848   848 F DEBUG   : 
02-25 17:10:37.363   848   848 F DEBUG   : backtrace:
02-25 17:10:37.363   848   848 F DEBUG   :     #00 pc 00042540  /system/lib/libc.so (tgkill+12)
02-25 17:10:37.364   848   848 F DEBUG   :     #01 pc 00040141  /system/lib/libc.so (pthread_kill+32)
02-25 17:10:37.364   848   848 F DEBUG   :     #02 pc 0001c79f  /system/lib/libc.so (raise+10)
02-25 17:10:37.364   848   848 F DEBUG   :     #03 pc 00027654  /system/vendor/lib/libRSDriver_adreno.so (__aeabi_ldiv0+8)
02-25 17:10:37.364   848   848 F DEBUG   :     #04 pc 00052d3d  /system/vendor/lib/libCB.so (cl_a5x_ddl_create_device_program+476)
02-25 17:10:37.364   848   848 F DEBUG   :     #05 pc 00057e2f  /system/vendor/lib/libCB.so (cl_a5x_create_utility_programs+542)
02-25 17:10:37.364   848   848 F DEBUG   :     #06 pc 0004feef  /system/vendor/lib/libCB.so (cl_a5x_initialize_global_gsl_state+22)
02-25 17:10:37.364   848   848 F DEBUG   :     #07 pc 00026e29  /system/vendor/lib/libCB.so (cb_common_initialize_global_gsl_state+32)
02-25 17:10:37.364   848   848 F DEBUG   :     #08 pc 00028653  /system/vendor/lib/libCB.so (cb_create_context+178)
02-25 17:10:37.364   848   848 F DEBUG   :     #09 pc 0000e2cd  /system/vendor/lib/librs_adreno.so
02-25 17:10:37.364   848   848 F DEBUG   :     #10 pc 000040a1  /system/vendor/lib/librs_adreno.so
02-25 17:10:37.364   848   848 F DEBUG   :     #11 pc 00004b23  /system/vendor/lib/librs_adreno.so (rsdVendorContextInit2+46)
02-25 17:10:37.364   848   848 F DEBUG   :     #12 pc 0001aaa7  /system/vendor/lib/libRSDriver_adreno.so (rsdHalInit+458)
02-25 17:10:37.365   848   848 F DEBUG   :     #13 pc 0002626b  /system/lib/libRS.so (_ZN7android12renderscript7Context11loadRuntimeEPKc+1442)
02-25 17:10:37.365   848   848 F DEBUG   :     #14 pc 0002630b  /system/lib/libRS.so (_ZN7android12renderscript7Context10loadDriverEb+18)
02-25 17:10:37.365   848   848 F DEBUG   :     #15 pc 00023c25  /system/lib/libRS.so (_ZN7android12renderscript7Context10threadProcEPv+388)
02-25 17:10:37.365   848   848 F DEBUG   :     #16 pc 0003fa43  /system/lib/libc.so (_ZL15__pthread_startPv+30)
02-25 17:10:37.365   848   848 F DEBUG   :     #17 pc 00019fd5  /system/lib/libc.so (__start_thread+6)
02-25 17:10:38.522   848   848 F DEBUG   : 
02-25 17:10:38.522   848   848 F DEBUG   : Tombstone written to: /data/tombstones/tombstone_07
02-25 20:50:41.359 28247 28247 E AndroidRuntime: *** FATAL EXCEPTION IN SYSTEM PROCESS: main
02-25 20:50:41.359 28247 28247 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke interface method 'android.content.pm.PackageInfo android.content.pm.IPackageManager.getPackageInfo(java.lang.String, int, int)' on a null object reference
02-25 20:50:41.359 28247 28247 E AndroidRuntime: 	at me.piebridge.brevent.a.a.a(HideApiOverride.java:31)
02-25 20:50:41.359 28247 28247 E AndroidRuntime: 	at me.piebridge.brevent.loader.Brevent.main(Brevent.java:106)
02-25 20:50:41.359 28247 28247 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
02-25 20:50:41.359 28247 28247 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:265)
02-25 20:50:41.360 28247 28247 E AndroidRuntime: Error reporting crash
02-25 20:50:41.360 28247 28247 E AndroidRuntime: java.lang.RuntimeException: Bad file descriptor
02-25 20:50:41.360 28247 28247 E AndroidRuntime: 	at android.os.BinderProxy.transactNative(Native Method)
02-25 20:50:41.360 28247 28247 E AndroidRuntime: 	at android.os.BinderProxy.transact(Binder.java:536)
02-25 20:50:41.360 28247 28247 E AndroidRuntime: 	at android.os.ServiceManagerProxy.getService(ServiceManagerNative.java:123)
02-25 20:50:41.360 28247 28247 E AndroidRuntime: 	at android.os.ServiceManager.getService(ServiceManager.java:55)
02-25 20:50:41.360 28247 28247 E AndroidRuntime: 	at android.app.ActivityManagerNative$1.create(ActivityManagerNative.java:2807)
02-25 20:50:41.360 28247 28247 E AndroidRuntime: 	at android.app.ActivityManagerNative$1.create(ActivityManagerNative.java:2805)
02-25 20:50:41.360 28247 28247 E AndroidRuntime: 	at android.util.Singleton.get(Singleton.java:34)
02-25 20:50:41.360 28247 28247 E AndroidRuntime: 	at android.app.ActivityManagerNative.getDefault(ActivityManagerNative.java:88)
02-25 20:50:41.360 28247 28247 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$UncaughtHandler.uncaughtException(RuntimeInit.java:104)
02-25 20:50:41.360 28247 28247 E AndroidRuntime: 	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:693)
02-25 20:50:41.360 28247 28247 E AndroidRuntime: 	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:690)
02-25 20:50:52.322 28284 28284 E AndroidRuntime: *** FATAL EXCEPTION IN SYSTEM PROCESS: main
02-25 20:50:52.322 28284 28284 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke interface method 'android.content.pm.PackageInfo android.content.pm.IPackageManager.getPackageInfo(java.lang.String, int, int)' on a null object reference
02-25 20:50:52.322 28284 28284 E AndroidRuntime: 	at me.piebridge.brevent.a.a.a(HideApiOverride.java:31)
02-25 20:50:52.322 28284 28284 E AndroidRuntime: 	at me.piebridge.brevent.loader.Brevent.main(Brevent.java:106)
02-25 20:50:52.322 28284 28284 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
02-25 20:50:52.322 28284 28284 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:265)
02-25 20:50:52.323 28284 28284 E AndroidRuntime: Error reporting crash
02-25 20:50:52.323 28284 28284 E AndroidRuntime: java.lang.RuntimeException: Bad file descriptor
02-25 20:50:52.323 28284 28284 E AndroidRuntime: 	at android.os.BinderProxy.transactNative(Native Method)
02-25 20:50:52.323 28284 28284 E AndroidRuntime: 	at android.os.BinderProxy.transact(Binder.java:536)
02-25 20:50:52.323 28284 28284 E AndroidRuntime: 	at android.os.ServiceManagerProxy.getService(ServiceManagerNative.java:123)
02-25 20:50:52.323 28284 28284 E AndroidRuntime: 	at android.os.ServiceManager.getService(ServiceManager.java:55)
02-25 20:50:52.323 28284 28284 E AndroidRuntime: 	at android.app.ActivityManagerNative$1.create(ActivityManagerNative.java:2807)
02-25 20:50:52.323 28284 28284 E AndroidRuntime: 	at android.app.ActivityManagerNative$1.create(ActivityManagerNative.java:2805)
02-25 20:50:52.323 28284 28284 E AndroidRuntime: 	at android.util.Singleton.get(Singleton.java:34)
02-25 20:50:52.323 28284 28284 E AndroidRuntime: 	at android.app.ActivityManagerNative.getDefault(ActivityManagerNative.java:88)
02-25 20:50:52.323 28284 28284 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$UncaughtHandler.uncaughtException(RuntimeInit.java:104)
02-25 20:50:52.323 28284 28284 E AndroidRuntime: 	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:693)
02-25 20:50:52.323 28284 28284 E AndroidRuntime: 	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:690)
02-25 20:51:31.810 28559 28559 E AndroidRuntime: *** FATAL EXCEPTION IN SYSTEM PROCESS: main
02-25 20:51:31.810 28559 28559 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke interface method 'android.content.pm.PackageInfo android.content.pm.IPackageManager.getPackageInfo(java.lang.String, int, int)' on a null object reference
02-25 20:51:31.810 28559 28559 E AndroidRuntime: 	at me.piebridge.brevent.a.a.a(HideApiOverride.java:31)
02-25 20:51:31.810 28559 28559 E AndroidRuntime: 	at me.piebridge.brevent.loader.Brevent.main(Brevent.java:106)
02-25 20:51:31.810 28559 28559 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
02-25 20:51:31.810 28559 28559 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:265)
02-25 20:51:31.811 28559 28559 E AndroidRuntime: Error reporting crash
02-25 20:51:31.811 28559 28559 E AndroidRuntime: java.lang.RuntimeException: Bad file descriptor
02-25 20:51:31.811 28559 28559 E AndroidRuntime: 	at android.os.BinderProxy.transactNative(Native Method)
02-25 20:51:31.811 28559 28559 E AndroidRuntime: 	at android.os.BinderProxy.transact(Binder.java:536)
02-25 20:51:31.811 28559 28559 E AndroidRuntime: 	at android.os.ServiceManagerProxy.getService(ServiceManagerNative.java:123)
02-25 20:51:31.811 28559 28559 E AndroidRuntime: 	at android.os.ServiceManager.getService(ServiceManager.java:55)
02-25 20:51:31.811 28559 28559 E AndroidRuntime: 	at android.app.ActivityManagerNative$1.create(ActivityManagerNative.java:2807)
02-25 20:51:31.811 28559 28559 E AndroidRuntime: 	at android.app.ActivityManagerNative$1.create(ActivityManagerNative.java:2805)
02-25 20:51:31.811 28559 28559 E AndroidRuntime: 	at android.util.Singleton.get(Singleton.java:34)
02-25 20:51:31.811 28559 28559 E AndroidRuntime: 	at android.app.ActivityManagerNative.getDefault(ActivityManagerNative.java:88)
02-25 20:51:31.811 28559 28559 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$UncaughtHandler.uncaughtException(RuntimeInit.java:104)
02-25 20:51:31.811 28559 28559 E AndroidRuntime: 	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:693)
02-25 20:51:31.811 28559 28559 E AndroidRuntime: 	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:690)
--- crash end ---
--- brevent start ---
02-25 20:49:25.477  4977  4987 D BreventServer: checking
02-25 20:49:30.662  4977  4987 I BreventServer: reset home tid to 2019
02-25 20:49:31.106  4977  4987 I BreventServer: reset home tid to 2019
02-25 20:49:33.654  4977  4987 D BreventServer: checking
02-25 20:49:33.683  4977  4987 E BreventServer: top: {} don't contains current: com.teslacoilsw.launcher
02-25 20:49:40.346  4977  4987 I BreventServer: reset home tid to 2019
02-25 20:50:29.755  4977  4987 I BreventServer: reset home tid to 2019
02-25 20:50:30.923  4977  4987 D BreventServer: checking
02-25 20:50:30.941  4977  4987 E BreventServer: top: {} don't contains current: com.teslacoilsw.launcher
02-25 20:50:32.491  4977  4987 D BreventServer: checking
02-25 20:50:35.916  4977  4987 D BreventServer: checking
02-25 20:50:37.162  4977  4987 I BreventServer: reset home tid to 2019
02-25 20:50:39.418  4977  4987 D BreventServer: checking
02-25 20:50:39.435  4977  4987 E BreventServer: top: {} don't contains current: com.teslacoilsw.launcher
--- brevent end ---
cannot listen port, please report bug to https://github.com/liudongmiao/Brevent/issues with log above
```

**Comment by liudongmiao** [comment]
请问这种情况是一直，但是只是偶尔？

**Comment by liudongmiao** [comment]
selinux问题，目前无解。
