### ISSUE TITLE
Bad Device Idle Settings

### ISSUE THREAD

**Issue by aviraxp** [liudongmiao/Brevent#158]
```
03-04 19:52:21.524 E/DeviceIdleController(3767): Bad device idle settings
03-04 19:52:21.524 E/DeviceIdleController(3767): java.lang.IllegalArgumentException: 'null' in 'null' is not a valid key-value pair
03-04 19:52:21.524 E/DeviceIdleController(3767):      at android.util.KeyValueListParser.setString(KeyValueListParser.java:57)
03-04 19:52:21.524 E/DeviceIdleController(3767):      at com.android.server.DeviceIdleController$Constants.updateConstants(DeviceIdleController.java:546)
03-04 19:52:21.524 E/DeviceIdleController(3767):      at com.android.server.DeviceIdleController$Constants.<init>(DeviceIdleController.java:518)
03-04 19:52:21.524 E/DeviceIdleController(3767):      at com.android.server.DeviceIdleController.onStart(DeviceIdleController.java:1017)
03-04 19:52:21.524 E/DeviceIdleController(3767):      at com.android.server.SystemServiceManager.startService(SystemServiceManager.java:109)
03-04 19:52:21.524 E/DeviceIdleController(3767):      at com.android.server.SystemServer.startOtherServices(SystemServer.java:642)
03-04 19:52:21.524 E/DeviceIdleController(3767):      at com.android.server.SystemServer.run(SystemServer.java:273)
03-04 19:52:21.524 E/DeviceIdleController(3767):      at com.android.server.SystemServer.main(SystemServer.java:171)
03-04 19:52:21.524 E/DeviceIdleController(3767):      at java.lang.reflect.Method.invoke(Native Method)
03-04 19:52:21.524 E/DeviceIdleController(3767):      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
03-04 19:52:21.524 E/DeviceIdleController(3767):      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
03-04 19:52:21.524 E/DeviceIdleController(3767):      at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:102)
```

**Comment by aviraxp** [comment]
不影响使用。只是开机会扔这个。

**Comment by liudongmiao** [comment]
这个看起来，不是黑域造成的吧...

**Comment by aviraxp** [comment]
说实话，我看着也不太像。。。但是在安装黑域之前，是没有这个的。。。
