### ISSUE TITLE
UI Crash when refreshing list

### ISSUE THREAD

**Issue by aviraxp** [liudongmiao/Brevent#193]
```
[03-08 15:53:49.383 E/AndroidRuntime(11911): java.lang.IndexOutOfBoundsException: Invalid index 1, size is 1
03-08 15:53:49.383 E/AndroidRuntime(11911): 	at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:255)
03-08 15:53:49.383 E/AndroidRuntime(11911): 	at java.util.ArrayList.get(ArrayList.java:308)
03-08 15:53:49.383 E/AndroidRuntime(11911): 	at me.piebridge.brevent.ui.j.a(AppsItemHandler.java:115)
03-08 15:53:49.383 E/AndroidRuntime(11911): 	at me.piebridge.brevent.ui.j.handleMessage(AppsItemHandler.java:49)
03-08 15:53:49.383 E/AndroidRuntime(11911): 	at android.os.Handler.dispatchMessage(Handler.java:102)
03-08 15:53:49.383 E/AndroidRuntime(11911): 	at android.os.Looper.loop(Looper.java:152)
03-08 15:53:49.383 E/AndroidRuntime(11911): 	at android.app.ActivityThread.main(ActivityThread.java:5497)
03-08 15:53:49.383 E/AndroidRuntime(11911): 	at java.lang.reflect.Method.invoke(Native Method)
03-08 15:53:49.383 E/AndroidRuntime(11911): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
03-08 15:53:49.383 E/AndroidRuntime(11911): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
03-08 15:53:49.383 E/AndroidRuntime(11911): 	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:102)
```

**Comment by liudongmiao** [comment]
这个地方，总是会极少数异常一下，很难根治。

**Comment by liudongmiao** [comment]
```java
        last = Math.min(last, appsInfoList.size());
        for (int i = first; i <= last; ++i) {
```
果然，写错了....
