### ISSUE TITLE
没有 ROOT 时可能的异常崩溃

### ISSUE THREAD

**Issue by liudongmiao** [liudongmiao/Brevent#197]
```
E/AndroidRuntime: FATAL EXCEPTION: IntentService[BreventIntentService]
E/AndroidRuntime: Process: me.piebridge.brevent, PID: 5755
E/AndroidRuntime: java.lang.NullPointerException: Attempt to invoke interface method 'java.util.Iterator java.util.List.iterator()' on a null object reference
E/AndroidRuntime: 	at me.piebridge.brevent.ui.BreventIntentService.a(BreventIntentService.java:34)
E/AndroidRuntime: 	at me.piebridge.brevent.ui.BreventIntentService.onHandleIntent(BreventIntentService.java:23)
E/AndroidRuntime: 	at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:68)
E/AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime: 	at android.os.Looper.loop(Looper.java:154)
E/AndroidRuntime: 	at android.os.HandlerThread.run(HandlerThread.java:61)
```

**Comment by liudongmiao** [comment]
十天未反馈，关闭。
