### ISSUE TITLE
使用Root模式後不能用adb模式打開

### ISSUE THREAD

**Issue by manhong2112** [liudongmiao/Brevent#226]
```
03-14 21:04:50.784 29991 29991 E AndroidRuntime: java.io.FileNotFoundException: /data/user_de/0/com.android.shell/brevent/libre
ader.so (Permission denied)
03-14 21:04:50.784 29991 29991 E AndroidRuntime:        at java.io.FileOutputStream.open(Native Method)
03-14 21:04:50.784 29991 29991 E AndroidRuntime:        at java.io.FileOutputStream.<init>(FileOutputStream.java:221)
03-14 21:04:50.784 29991 29991 E AndroidRuntime:        at java.io.FileOutputStream.<init>(FileOutputStream.java:169)
03-14 21:04:50.784 29991 29991 E AndroidRuntime:        at me.piebridge.brevent.loader.Brevent.a(Brevent.java:95)
03-14 21:04:50.784 29991 29991 E AndroidRuntime:        at me.piebridge.brevent.loader.Brevent.main(Brevent.java:123)
03-14 21:04:50.784 29991 29991 E AndroidRuntime:        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
03-14 21:04:50.784 29991 29991 E AndroidRuntime:        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:262)
```

```
gemini:/data/user_de/0/com.android.shell $ ls -la
total 96
drwx------   7 shell  shell   4096 2017-03-14 16:29 .
drwxrwx--x 306 system system 12288 2017-03-14 21:01 ..
drwx------   2 root   root    4096 2017-03-08 00:05 brevent
drwxrwx--x   2 shell  shell   4096 2017-03-14 16:29 cache
drwxrwx--x   2 shell  shell   4096 2017-03-14 08:01 code_cache
drwx------   3 shell  shell   4096 2017-03-14 07:59 files
-rw-------   1 root   root    4902 2017-03-14 16:29 me.piebridge.brevent.list
drwxrwx--x   2 shell  shell   4096 2017-03-14 08:01 shared_prefs
```

然後我就改了權限, `chown -R shell:shell brevent`
於是能用了, 嗯

**Comment by liudongmiao** [comment]
这个，明显我不会也不能解决嘛...

**Comment by manhong2112** [comment]
呃...至少要跟你提一下吧...那...close掉?

**Comment by liudongmiao** [comment]
我知道这个事，并且也没有好的方法。。。

**Comment by manhong2112** [comment]
我知道...要root才能存取改權限...
話說為甚麼要改成root...root權限不能直接存取shell嗎
