### ISSUE TITLE
黑域在 Sony Z3C 上启动失败

### ISSUE THREAD

**Issue by beginor** [liudongmiao/Brevent#235]
系统基于是 Sony 官方系统 6.0.1 修改的 SLIMM ROM 3.8， 连接 USB 执行命令的操作记录如下：
```shell
Last login: Wed Mar 15 06:02:08 on ttys000
A1502:~ zhang$ adb devices
List of devices attached
YT9115TTM1	device

A1502:~ zhang$ adb -d shell /data/app/me.piebridge.brevent-2/lib/arm/libbootstrap.so
checking............cannot listen port
please report bug to https://github.com/liudongmiao/Brevent/issues with log below
--- crash start ---
>>> logcat -b crash -t '03-16 06:12:42.000' -d
03-16 06:12:44.280   333   333 E AndroidRuntime: *** FATAL EXCEPTION IN SYSTEM PROCESS: main
03-16 06:12:44.280   333   333 E AndroidRuntime: java.io.FileNotFoundException: /data/user/0/com.android.shell/brevent/libreader.so: open failed: EACCES (Permission denied)
03-16 06:12:44.280   333   333 E AndroidRuntime: 	at libcore.io.IoBridge.open(IoBridge.java:452)
03-16 06:12:44.280   333   333 E AndroidRuntime: 	at java.io.FileOutputStream.<init>(FileOutputStream.java:87)
03-16 06:12:44.280   333   333 E AndroidRuntime: 	at java.io.FileOutputStream.<init>(FileOutputStream.java:72)
03-16 06:12:44.280   333   333 E AndroidRuntime: 	at me.piebridge.brevent.loader.Brevent.a(Brevent.java:95)
03-16 06:12:44.280   333   333 E AndroidRuntime: 	at me.piebridge.brevent.loader.Brevent.main(Brevent.java:123)
03-16 06:12:44.280   333   333 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
03-16 06:12:44.280   333   333 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:251)
03-16 06:12:44.280   333   333 E AndroidRuntime: Caused by: android.system.ErrnoException: open failed: EACCES (Permission denied)
03-16 06:12:44.280   333   333 E AndroidRuntime: 	at libcore.io.Posix.open(Native Method)
03-16 06:12:44.280   333   333 E AndroidRuntime: 	at libcore.io.BlockGuardOs.open(BlockGuardOs.java:186)
03-16 06:12:44.280   333   333 E AndroidRuntime: 	at libcore.io.IoBridge.open(IoBridge.java:438)
03-16 06:12:44.280   333   333 E AndroidRuntime: 	... 6 more
03-16 06:12:44.303   333   333 E AndroidRuntime: Error reporting crash
03-16 06:12:44.303   333   333 E AndroidRuntime: java.lang.RuntimeException: Bad file descriptor
03-16 06:12:44.303   333   333 E AndroidRuntime: 	at android.os.BinderProxy.transactNative(Native Method)
03-16 06:12:44.303   333   333 E AndroidRuntime: 	at android.os.BinderProxy.transact(Binder.java:503)
03-16 06:12:44.303   333   333 E AndroidRuntime: 	at android.os.ServiceManagerProxy.getService(ServiceManagerNative.java:123)
03-16 06:12:44.303   333   333 E AndroidRuntime: 	at android.os.ServiceManager.getService(ServiceManager.java:55)
03-16 06:12:44.303   333   333 E AndroidRuntime: 	at android.app.ActivityManagerNative$1.create(ActivityManagerNative.java:2611)
03-16 06:12:44.303   333   333 E AndroidRuntime: 	at android.app.ActivityManagerNative$1.create(ActivityManagerNative.java:2609)
03-16 06:12:44.303   333   333 E AndroidRuntime: 	at android.util.Singleton.get(Singleton.java:34)
03-16 06:12:44.303   333   333 E AndroidRuntime: 	at android.app.ActivityManagerNative.getDefault(ActivityManagerNative.java:89)
03-16 06:12:44.303   333   333 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$UncaughtHandler.uncaughtException(RuntimeInit.java:90)
03-16 06:12:44.303   333   333 E AndroidRuntime: 	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:693)
03-16 06:12:44.303   333   333 E AndroidRuntime: 	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:690)
--- crash end ---
--- brevent start ---
>>> logcat -b main -t '03-16 06:12:42.000' -d -s BreventLoader BreventServer
--- brevent end ---
cannot listen port, please report bug to https://github.com/liudongmiao/Brevent/issues with log above
```

**Comment by liudongmiao** [comment]
删除 /data/user/0/com.android.shell/ 下的文件，再使用。
你要能之前使用过 root 模式？

**Comment by beginor** [comment]
好的，谢谢！ 我试试看。 是的， 因为从 play 上下载的旧版本是可以用 root 模式启动的， 所以用过 root 模式。

**Comment by beginor** [comment]
使用 `adb shell` 连接到手机上， 用 `su` 权限删掉 `/data/user/0/com.android.shell/` 目录之后， 再次执行， 还是出错：

```shell
A1502:~ zhang$ adb -d shell /data/app/me.piebridge.brevent-2/lib/arm/libbootstrap.so
checking...brevent_server started, pid: 25739
checking for stable..quited

please report bug to https://github.com/liudongmiao/Brevent/issues with log below
--- crash start ---
>>> logcat -b crash -t '03-16 19:18:36.000' -d
03-16 19:18:37.427 25739 25739 E AndroidRuntime: *** FATAL EXCEPTION IN SYSTEM PROCESS: main
03-16 19:18:37.427 25739 25739 E AndroidRuntime: java.lang.UnsupportedOperationException: Can't make sure directory: /data/user/0/com.android.shell/brevent
03-16 19:18:37.427 25739 25739 E AndroidRuntime: 	at me.piebridge.brevent.loader.Brevent.a(Brevent.java:89)
03-16 19:18:37.427 25739 25739 E AndroidRuntime: 	at me.piebridge.brevent.loader.Brevent.main(Brevent.java:123)
03-16 19:18:37.427 25739 25739 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
03-16 19:18:37.427 25739 25739 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:251)
03-16 19:18:37.428 25739 25739 E AndroidRuntime: Error reporting crash
03-16 19:18:37.428 25739 25739 E AndroidRuntime: java.lang.RuntimeException: Bad file descriptor
03-16 19:18:37.428 25739 25739 E AndroidRuntime: 	at android.os.BinderProxy.transactNative(Native Method)
03-16 19:18:37.428 25739 25739 E AndroidRuntime: 	at android.os.BinderProxy.transact(Binder.java:503)
03-16 19:18:37.428 25739 25739 E AndroidRuntime: 	at android.os.ServiceManagerProxy.getService(ServiceManagerNative.java:123)
03-16 19:18:37.428 25739 25739 E AndroidRuntime: 	at android.os.ServiceManager.getService(ServiceManager.java:55)
03-16 19:18:37.428 25739 25739 E AndroidRuntime: 	at android.app.ActivityManagerNative$1.create(ActivityManagerNative.java:2611)
03-16 19:18:37.428 25739 25739 E AndroidRuntime: 	at android.app.ActivityManagerNative$1.create(ActivityManagerNative.java:2609)
03-16 19:18:37.428 25739 25739 E AndroidRuntime: 	at android.util.Singleton.get(Singleton.java:34)
03-16 19:18:37.428 25739 25739 E AndroidRuntime: 	at android.app.ActivityManagerNative.getDefault(ActivityManagerNative.java:89)
03-16 19:18:37.428 25739 25739 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$UncaughtHandler.uncaughtException(RuntimeInit.java:90)
03-16 19:18:37.428 25739 25739 E AndroidRuntime: 	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:693)
03-16 19:18:37.428 25739 25739 E AndroidRuntime: 	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:690)
--- crash end ---
--- brevent start ---
>>> logcat -b main -t '03-16 19:18:36.000' -d -s BreventLoader BreventServer
03-16 19:18:37.427 25739 25739 W BreventLoader: Can't make sure directory: /data/user/0/com.android.shell/brevent
--- brevent end ---
cannot listen port, please report bug to https://github.com/liudongmiao/Brevent/issues with log above
```

**Comment by liudongmiao** [comment]
adb -d shell id 
给下这个结果

**Comment by beginor** [comment]
`adb -d shell id` 输出结果为：

uid=2000(shell) gid=2000(shell) groups=2000(shell),1004(input),1007(log),1011(adb),1015(sdcard_rw),1026(drmrpc),1028(sdcard_r),2993(trimarea),3001(net_bt_admin),3002(net_bt),3003(inet),3006(net_bw_stats) context=u:r:shell:s0

重启了一下手机， 发现可以启动黑域了 😒

**Comment by liudongmiao** [comment]
十天未反馈，关闭。
