### ISSUE TITLE
偶尔两个界面问题

### ISSUE THREAD

**Issue by aviraxp** [liudongmiao/Brevent#254]
```
03-19 23:08:05.887 E/AndroidRuntime(18246): FATAL EXCEPTION: main
03-19 23:08:05.887 E/AndroidRuntime(18246): Process: me.piebridge.brevent, PID: 18246
03-19 23:08:05.887 E/AndroidRuntime(18246): java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
03-19 23:08:05.887 E/AndroidRuntime(18246): 	at android.app.FragmentManagerImpl.checkStateLoss(FragmentManager.java:1411)
03-19 23:08:05.887 E/AndroidRuntime(18246): 	at android.app.FragmentManagerImpl.enqueueAction(FragmentManager.java:1429)
03-19 23:08:05.887 E/AndroidRuntime(18246): 	at android.app.BackStackRecord.commitInternal(BackStackRecord.java:687)
03-19 23:08:05.887 E/AndroidRuntime(18246): 	at android.app.BackStackRecord.commit(BackStackRecord.java:663)
03-19 23:08:05.887 E/AndroidRuntime(18246): 	at android.app.DialogFragment.dismissInternal(DialogFragment.java:301)
03-19 23:08:05.887 E/AndroidRuntime(18246): 	at android.app.DialogFragment.dismiss(DialogFragment.java:267)
03-19 23:08:05.887 E/AndroidRuntime(18246): 	at me.piebridge.brevent.ui.BreventActivity.k(BreventActivity.java:286)
03-19 23:08:05.887 E/AndroidRuntime(18246): 	at me.piebridge.brevent.ui.BreventActivity.d(BreventActivity.java:280)
03-19 23:08:05.887 E/AndroidRuntime(18246): 	at me.piebridge.brevent.ui.h.a(AppsInfoTask.java:64)
03-19 23:08:05.887 E/AndroidRuntime(18246): 	at me.piebridge.brevent.ui.h.onPostExecute(AppsInfoTask.java:18)
03-19 23:08:05.887 E/AndroidRuntime(18246): 	at android.os.AsyncTask.finish(AsyncTask.java:651)
03-19 23:08:05.887 E/AndroidRuntime(18246): 	at android.os.AsyncTask.access$500(AsyncTask.java:180)
03-19 23:08:05.887 E/AndroidRuntime(18246): 	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:668)
03-19 23:08:05.887 E/AndroidRuntime(18246): 	at android.os.Handler.dispatchMessage(Handler.java:102)
03-19 23:08:05.887 E/AndroidRuntime(18246): 	at android.os.Looper.loop(Looper.java:152)
03-19 23:08:05.887 E/AndroidRuntime(18246): 	at android.app.ActivityThread.main(ActivityThread.java:5497)
03-19 23:08:05.887 E/AndroidRuntime(18246): 	at java.lang.reflect.Method.invoke(Native Method)
03-19 23:08:05.887 E/AndroidRuntime(18246): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
03-19 23:08:05.887 E/AndroidRuntime(18246): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
03-19 23:08:05.887 E/AndroidRuntime(18246): 	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:102)
03-19 23:09:46.497 E/ActivityThread(19496): Activity me.piebridge.brevent.ui.BreventSettings has leaked ServiceConnection Handler (me.piebridge.a.c) {c3fc6c8} that was originally bound here
03-19 23:09:46.497 E/ActivityThread(19496): android.app.ServiceConnectionLeaked: Activity me.piebridge.brevent.ui.BreventSettings has leaked ServiceConnection Handler (me.piebridge.a.c) {c3fc6c8} that was originally bound here
03-19 23:09:46.497 E/ActivityThread(19496): 	at android.app.LoadedApk$ServiceDispatcher.<init>(LoadedApk.java:1120)
03-19 23:09:46.497 E/ActivityThread(19496): 	at android.app.LoadedApk.getServiceDispatcher(LoadedApk.java:1014)
03-19 23:09:46.497 E/ActivityThread(19496): 	at android.app.ContextImpl.bindServiceCommon(ContextImpl.java:1319)
03-19 23:09:46.497 E/ActivityThread(19496): 	at android.app.ContextImpl.bindService(ContextImpl.java:1302)
03-19 23:09:46.497 E/ActivityThread(19496): 	at android.content.ContextWrapper.bindService(ContextWrapper.java:605)
03-19 23:09:46.497 E/ActivityThread(19496): 	at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
03-19 23:09:46.497 E/ActivityThread(19496): 	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:334)
03-19 23:09:46.497 E/ActivityThread(19496): 	at android.content.ContextWrapper.bindService(<Xposed>)
03-19 23:09:46.497 E/ActivityThread(19496): 	at me.piebridge.a.a.p(DonateActivity.java:133)
03-19 23:09:46.497 E/ActivityThread(19496): 	at me.piebridge.a.a.f(DonateActivity.java:108)
03-19 23:09:46.497 E/ActivityThread(19496): 	at me.piebridge.a.a.onStart(DonateActivity.java:97)
03-19 23:09:46.497 E/ActivityThread(19496): 	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1277)
03-19 23:09:46.497 E/ActivityThread(19496): 	at android.app.Activity.performStart(Activity.java:6306)
03-19 23:09:46.497 E/ActivityThread(19496): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2415)
03-19 23:09:46.497 E/ActivityThread(19496): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2535)
03-19 23:09:46.497 E/ActivityThread(19496): 	at android.app.ActivityThread.access$900(ActivityThread.java:155)
03-19 23:09:46.497 E/ActivityThread(19496): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1380)
03-19 23:09:46.497 E/ActivityThread(19496): 	at android.os.Handler.dispatchMessage(Handler.java:102)
03-19 23:09:46.497 E/ActivityThread(19496): 	at android.os.Looper.loop(Looper.java:152)
03-19 23:09:46.497 E/ActivityThread(19496): 	at android.app.ActivityThread.main(ActivityThread.java:5497)
03-19 23:09:46.497 E/ActivityThread(19496): 	at java.lang.reflect.Method.invoke(Native Method)
03-19 23:09:46.497 E/ActivityThread(19496): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
03-19 23:09:46.497 E/ActivityThread(19496): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
03-19 23:09:46.497 E/ActivityThread(19496): 	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:102)
```

**Comment by liudongmiao** [comment]
去掉 xposed，否则我不处理，嗯，就这样...

这两处，我都是用完即释放的。

**Comment by liudongmiao** [comment]
1. dismiss 的那个，我在 0.9.4 里修了

2. 第二个，暂时不处理了，没有收到任何反馈说有错。

**Comment by aviraxp** [comment]
第二个是我写的一个模块的锅，今天修了

**Comment by liudongmiao** [comment]
让我看看怎么修的～给个地址。

**Comment by aviraxp** [comment]
尴尬，本来以为是对 bindService 的处理有点问题，就先去掉了，结果发现问题依旧。

现在来看，基本是幸运破解器的锅。
