### ISSUE TITLE
電腦ADB無效

### ISSUE THREAD

**Issue by Small-Ku** [liudongmiao/Brevent#264]
電腦上面用的ADB指令
```
--- crash start ---
>>> logcat -b crash -t '03-20 23:14:43.000' -d
03-20 23:14:44.447 19310 19310 E AndroidRuntime: *** FATAL EXCEPTION IN SYSTEM PROCESS: main
03-20 23:14:44.447 19310 19310 E AndroidRuntime: java.io.FileNotFoundException: /data/user_de/0/com.android.shell/brevent/libreader.so (Permission denied)
03-20 23:14:44.447 19310 19310 E AndroidRuntime:        at java.io.FileOutputStream.open(Native Method)
03-20 23:14:44.447 19310 19310 E AndroidRuntime:        at java.io.FileOutputStream.<init>(FileOutputStream.java:221)
03-20 23:14:44.447 19310 19310 E AndroidRuntime:        at java.io.FileOutputStream.<init>(FileOutputStream.java:169)
03-20 23:14:44.447 19310 19310 E AndroidRuntime:        at me.piebridge.brevent.loader.Brevent.a(Brevent.java:95)
03-20 23:14:44.447 19310 19310 E AndroidRuntime:        at me.piebridge.brevent.loader.Brevent.main(Brevent.java:123)
03-20 23:14:44.447 19310 19310 E AndroidRuntime:        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
03-20 23:14:44.447 19310 19310 E AndroidRuntime:        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:262)
03-20 23:14:44.448 19310 19310 E AndroidRuntime: Error reporting crash
03-20 23:14:44.448 19310 19310 E AndroidRuntime: java.lang.RuntimeException: Bad file descriptor
03-20 23:14:44.448 19310 19310 E AndroidRuntime:        at android.os.BinderProxy.transactNative(Native Method)
03-20 23:14:44.448 19310 19310 E AndroidRuntime:        at android.os.BinderProxy.transact(Binder.java:615)
03-20 23:14:44.448 19310 19310 E AndroidRuntime:        at android.os.ServiceManagerProxy.getService(ServiceManagerNative.java:123)
03-20 23:14:44.448 19310 19310 E AndroidRuntime:        at android.os.ServiceManager.getService(ServiceManager.java:55)
03-20 23:14:44.448 19310 19310 E AndroidRuntime:        at android.app.ActivityManagerNative$1.create(ActivityManagerNative.java:3049)
03-20 23:14:44.448 19310 19310 E AndroidRuntime:        at android.app.ActivityManagerNative$1.create(ActivityManagerNative.java:3048)
03-20 23:14:44.448 19310 19310 E AndroidRuntime:        at android.util.Singleton.get(Singleton.java:34)
03-20 23:14:44.448 19310 19310 E AndroidRuntime:        at android.app.ActivityManagerNative.getDefault(ActivityManagerNative.java:86)
03-20 23:14:44.448 19310 19310 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$UncaughtHandler.uncaughtException(RuntimeInit.java:97)
03-20 23:14:44.448 19310 19310 E AndroidRuntime:        at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1068)
03-20 23:14:44.448 19310 19310 E AndroidRuntime:        at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1063)
--- crash end ---
--- brevent start ---
>>> logcat -b main -t '03-20 23:14:43.000' -d -s BreventLoader BreventServer
--- brevent end ---
cannot listen port, please report bug to https://github.com/liudongmiao/Brevent/issues with log above
```

**Comment by liudongmiao** [comment]
1. 删除 /data/user_de/0/com.android.shell/ 下所有文件
2. 不要试图使用任何第三方脚本以 root 方式调用黑域
3. 然后重新执行黑域提供的脚本
