### ISSUE TITLE
偶尔手机重启

### ISSUE THREAD

**Issue by liudongmiao** [liudongmiao/Brevent#280]
```
03-23 04:44:15.483 10885 10885 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke interface method 'java.util.List android.view.accessibility.IAccessibilityManager.getEnabledAccessibilityServiceList(int, int)' on a null object reference
03-23 04:44:15.483 10885 10885 E AndroidRuntime:        at me.piebridge.brevent.server.BreventServer.d(BreventServer.java:397)
03-23 04:44:15.483 10885 10885 E AndroidRuntime:        at me.piebridge.brevent.server.BreventServer.h(BreventServer.java:613)
03-23 04:44:15.483 10885 10885 E AndroidRuntime:        at me.piebridge.brevent.server.BreventServer.handleMessage(BreventServer.java:320)
03-23 04:44:15.483 10885 10885 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:102)
03-23 04:44:15.483 10885 10885 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:154)
03-23 04:44:15.483 10885 10885 E AndroidRuntime:        at me.piebridge.brevent.server.BreventServer.y(BreventServer.java:1450)
03-23 04:44:15.483 10885 10885 E AndroidRuntime:        at me.piebridge.brevent.server.BreventServer.main(BreventServer.java:1455)
03-23 04:44:15.483 10885 10885 E AndroidRuntime:        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
03-23 04:44:15.483 10885 10885 E AndroidRuntime:        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:262)
03-23 04:44:15.520 18546 18546 E AndroidRuntime: FATAL EXCEPTION: main
```

```
03-23 10:43:04.593  9888  9888 F DEBUG   : backtrace:
03-23 10:43:04.594  9888  9888 F DEBUG   :     #00 pc 000000000006b2ec  /system/lib64/libc.so (tgkill+8)
03-23 10:43:04.594  9888  9888 F DEBUG   :     #01 pc 0000000000068788  /system/lib64/libc.so (pthread_kill+64)
03-23 10:43:04.594  9888  9888 F DEBUG   :     #02 pc 0000000000023ce8  /system/lib64/libc.so (raise+24)
03-23 10:43:04.594  9888  9888 F DEBUG   :     #03 pc 000000000001c76c  /system/lib64/libc.so (abort+52)
03-23 10:43:04.594  9888  9888 F DEBUG   :     #04 pc 00000000004300fc  /system/lib64/libart.so (_ZN3art7Runtime5AbortEPKc+456)
03-23 10:43:04.594  9888  9888 F DEBUG   :     #05 pc 00000000000e5818  /system/lib64/libart.so (_ZN3art10LogMessageD2Ev+1576)
03-23 10:43:04.594  9888  9888 F DEBUG   :     #06 pc 000000000024c328  /system/lib64/libart.so (_ZN3art22IndirectReferenceTable3AddEjPNS_6mirror6ObjectE+308)
03-23 10:43:04.594  9888  9888 F DEBUG   :     #07 pc 00000000002ef5b4  /system/lib64/libart.so (_ZN3art9JavaVMExt12AddGlobalRefEPNS_6ThreadEPNS_6mirror6ObjectE+60)
03-23 10:43:04.594  9888  9888 F DEBUG   :     #08 pc 000000000032a064  /system/lib64/libart.so (_ZN3art3JNI12NewGlobalRefEP7_JNIEnvP8_jobject+600)
03-23 10:43:04.594  9888  9888 F DEBUG   :     #09 pc 00000000000fc844  /system/lib64/libandroid_runtime.so (_ZN7android20ibinderForJavaObjectEP7_JNIEnvP8_jobject+516)
03-23 10:43:04.594  9888  9888 F DEBUG   :     #10 pc 00000000000f15b0  /system/lib64/libandroid_runtime.so
03-23 10:43:04.594  9888  9888 F DEBUG   :     #11 pc 0000000001f2b720  /system/framework/arm64/boot-framework.oat (offset 0x1686000) (android.os.Parcel.nativeWriteStrongBinder+156)
03-23 10:43:04.594  9888  9888 F DEBUG   :     #12 pc 0000000001f35f9c  /system/framework/arm64/boot-framework.oat (offset 0x1686000) (android.os.Parcel.writeStrongBinder+56)
03-23 10:43:04.594  9888  9888 F DEBUG   :     #13 pc 00000000017c9bc4  /system/framework/arm64/boot-framework.oat (offset 0x1686000) (android.app.IActivityManager$ContentProviderHolder.writeToParcel+192)
03-23 10:43:04.594  9888  9888 F DEBUG   :     #14 pc 00000000000d2534  /system/lib64/libart.so (art_quick_invoke_stub+580)
03-23 10:43:04.594  9888  9888 F DEBUG   :     #15 pc 00000000000df200  /system/lib64/libart.so (_ZN3art9ArtMethod6InvokeEPNS_6ThreadEPjjPNS_6JValueEPKc+204)
03-23 10:43:04.594  9888  9888 F DEBUG   :     #16 pc 000000000028eefc  /system/lib64/libart.so (_ZN3art11interpreter34ArtInterpreterToCompiledCodeBridgeEPNS_6ThreadEPNS_9ArtMethodEPKNS_7DexFile8CodeItemEPNS_11ShadowFrameEPNS_6JValueE+312)
03-23 10:43:04.594  9888  9888 F DEBUG   :     #17 pc 0000000000287ed8  /system/lib64/libart.so (_ZN3art11interpreter6DoCallILb0ELb0EEEbPNS_9ArtMethodEPNS_6ThreadERNS_11ShadowFrameEPKNS_11InstructionEtPNS_6JValueE+592)
03-23 10:43:04.594  9888  9888 F DEBUG   :     #18 pc 0000000000557e60  /system/lib64/libart.so (MterpInvokeVirtualQuick+452)
03-23 10:43:04.594  9888  9888 F DEBUG   :     #19 pc 00000000000c8c94  /system/lib64/libart.so (ExecuteMterpImpl+29972)
```

**Comment by liudongmiao** [comment]
```
03-23 10:43:04.313  9888  9888 F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
03-23 10:43:04.314  9888  9888 F DEBUG   : Build fingerprint: 'google/sailfish/sailfish:7.1.1/NOF27B/3687361:user/release-keys'
03-23 10:43:04.314  9888  9888 F DEBUG   : Revision: '0'
03-23 10:43:04.314  9888  9888 F DEBUG   : ABI: 'arm64'
03-23 10:43:04.314  9888  9888 F DEBUG   : pid: 18779, tid: 19225, name: Binder:18779_4  >>> system_server <<<
03-23 10:43:04.314  9888  9888 F DEBUG   : signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------
03-23 10:43:04.319  9888  9888 F DEBUG   : Abort message: 'art/runtime/indirect_reference_table.cc:132] JNI ERROR (app bug): global reference table overflow (max=51200)'
03-23 10:43:04.319  9888  9888 F DEBUG   :     x0   0000000000000000  x1   0000000000004b19  x2   0000000000000006  x3   0000000000000008
03-23 10:43:04.319  9888  9888 F DEBUG   :     x4   0000000000000162  x5   0000000000000000  x6   0000000000000000  x7   feff666e6b61686b
03-23 10:43:04.319  9888  9888 F DEBUG   :     x8   0000000000000083  x9   ffffffffffffffdf  x10  0000000000000000  x11  0000000000000001
03-23 10:43:04.319  9888  9888 F DEBUG   :     x12  ffffffffffffffff  x13  ffffffffffffffff  x14  ff00000000000000  x15  ffffffffffffffff
03-23 10:43:04.319  9888  9888 F DEBUG   :     x16  0000007f06c7eee0  x17  0000007f06c282e4  x18  0000000000000000  x19  0000007edc4f34f8
03-23 10:43:04.319  9888  9888 F DEBUG   :     x20  0000000000000006  x21  0000007edc4f3450  x22  000000000000000b  x23  0000007f03586918
03-23 10:43:04.319  9888  9888 F DEBUG   :     x24  000000000000000a  x25  ffffffffffffffff  x26  0000000000002ed5  x27  0000007edc4f11c1
03-23 10:43:04.319  9888  9888 F DEBUG   :     x28  0000007f035fc740  x29  0000007edc4f10c0  x30  0000007f06c2578c
03-23 10:43:04.319  9888  9888 F DEBUG   :     sp   0000007edc4f10a0  pc   0000007f06c282ec  pstate 0000000060000000
03-23 10:43:04.593  9888  9888 F DEBUG   : 
03-23 10:43:04.593  9888  9888 F DEBUG   : backtrace:
03-23 10:43:04.594  9888  9888 F DEBUG   :     #00 pc 000000000006b2ec  /system/lib64/libc.so (tgkill+8)
03-23 10:43:04.594  9888  9888 F DEBUG   :     #01 pc 0000000000068788  /system/lib64/libc.so (pthread_kill+64)
03-23 10:43:04.594  9888  9888 F DEBUG   :     #02 pc 0000000000023ce8  /system/lib64/libc.so (raise+24)
03-23 10:43:04.594  9888  9888 F DEBUG   :     #03 pc 000000000001c76c  /system/lib64/libc.so (abort+52)
03-23 10:43:04.594  9888  9888 F DEBUG   :     #04 pc 00000000004300fc  /system/lib64/libart.so (_ZN3art7Runtime5AbortEPKc+456)
03-23 10:43:04.594  9888  9888 F DEBUG   :     #05 pc 00000000000e5818  /system/lib64/libart.so (_ZN3art10LogMessageD2Ev+1576)
03-23 10:43:04.594  9888  9888 F DEBUG   :     #06 pc 000000000024c328  /system/lib64/libart.so (_ZN3art22IndirectReferenceTable3AddEjPNS_6mirror6ObjectE+308)
03-23 10:43:04.594  9888  9888 F DEBUG   :     #07 pc 00000000002ef5b4  /system/lib64/libart.so (_ZN3art9JavaVMExt12AddGlobalRefEPNS_6ThreadEPNS_6mirror6ObjectE+60)
03-23 10:43:04.594  9888  9888 F DEBUG   :     #08 pc 000000000032a064  /system/lib64/libart.so (_ZN3art3JNI12NewGlobalRefEP7_JNIEnvP8_jobject+600)
03-23 10:43:04.594  9888  9888 F DEBUG   :     #09 pc 00000000000fc844  /system/lib64/libandroid_runtime.so (_ZN7android20ibinderForJavaObjectEP7_JNIEnvP8_jobject+516)
03-23 10:43:04.594  9888  9888 F DEBUG   :     #10 pc 00000000000f15b0  /system/lib64/libandroid_runtime.so
03-23 10:43:04.594  9888  9888 F DEBUG   :     #11 pc 0000000001f2b720  /system/framework/arm64/boot-framework.oat (offset 0x1686000) (android.os.Parcel.nativeWriteStrongBinder+156)
03-23 10:43:04.594  9888  9888 F DEBUG   :     #12 pc 0000000001f35f9c  /system/framework/arm64/boot-framework.oat (offset 0x1686000) (android.os.Parcel.writeStrongBinder+56)
03-23 10:43:04.594  9888  9888 F DEBUG   :     #13 pc 00000000017c9bc4  /system/framework/arm64/boot-framework.oat (offset 0x1686000) (android.app.IActivityManager$ContentProviderHolder.writeToParcel+192)
03-23 10:43:04.594  9888  9888 F DEBUG   :     #14 pc 00000000000d2534  /system/lib64/libart.so (art_quick_invoke_stub+580)
03-23 10:43:04.594  9888  9888 F DEBUG   :     #15 pc 00000000000df200  /system/lib64/libart.so (_ZN3art9ArtMethod6InvokeEPNS_6ThreadEPjjPNS_6JValueEPKc+204)
03-23 10:43:04.594  9888  9888 F DEBUG   :     #16 pc 000000000028eefc  /system/lib64/libart.so (_ZN3art11interpreter34ArtInterpreterToCompiledCodeBridgeEPNS_6ThreadEPNS_9ArtMethodEPKNS_7DexFile8CodeItemEPNS_11ShadowFrameEPNS_6JValueE+312)
03-23 10:43:04.594  9888  9888 F DEBUG   :     #17 pc 0000000000287ed8  /system/lib64/libart.so (_ZN3art11interpreter6DoCallILb0ELb0EEEbPNS_9ArtMethodEPNS_6ThreadERNS_11ShadowFrameEPKNS_11InstructionEtPNS_6JValueE+592)
03-23 10:43:04.594  9888  9888 F DEBUG   :     #18 pc 0000000000557e60  /system/lib64/libart.so (MterpInvokeVirtualQuick+452)
03-23 10:43:04.594  9888  9888 F DEBUG   :     #19 pc 00000000000c8c94  /system/lib64/libart.so (ExecuteMterpImpl+29972)
```

**Comment by liudongmiao** [comment]
都已经处理。
