### ISSUE TITLE
MagiskSU授权的root无法运行，以前用SuperSU没这个问题

### ISSUE THREAD

**Issue by wzhy90** [liudongmiao/Brevent#408]
```
--- crash start ---
>>> logcat -b crash -t '04-10 11:53:42.000' -d
04-10 11:53:43.897 25769 25769 E AndroidRuntime: *** FATAL EXCEPTION IN SYSTEM PROCESS: main
04-10 11:53:43.897 25769 25769 E AndroidRuntime: java.lang.reflect.InvocationTargetException
04-10 11:53:43.897 25769 25769 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
04-10 11:53:43.897 25769 25769 E AndroidRuntime: 	at me.piebridge.brevent.server.BreventServer.main(BreventServer.java:1582)
04-10 11:53:43.897 25769 25769 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
04-10 11:53:43.897 25769 25769 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:262)
04-10 11:53:43.897 25769 25769 E AndroidRuntime: Caused by: me.piebridge.brevent.server.d$a: Can't dump activities
04-10 11:53:43.897 25769 25769 E AndroidRuntime: 	at me.piebridge.brevent.server.d.d(HideApi.java:327)
04-10 11:53:43.897 25769 25769 E AndroidRuntime: 	at me.piebridge.brevent.server.BreventServer.<init>(BreventServer.java:217)
04-10 11:53:43.897 25769 25769 E AndroidRuntime: 	at me.piebridge.brevent.server.BreventServer.startBreventServer(BreventServer.java:1524)
04-10 11:53:43.897 25769 25769 E AndroidRuntime: 	... 4 more
04-10 11:53:43.900 25769 25769 E AndroidRuntime: Error reporting crash
04-10 11:53:43.900 25769 25769 E AndroidRuntime: java.lang.RuntimeException: Bad file descriptor
04-10 11:53:43.900 25769 25769 E AndroidRuntime: 	at android.os.BinderProxy.transactNative(Native Method)
04-10 11:53:43.900 25769 25769 E AndroidRuntime: 	at android.os.BinderProxy.transact(Binder.java:615)
04-10 11:53:43.900 25769 25769 E AndroidRuntime: 	at android.app.ActivityManagerProxy.handleApplicationCrash(ActivityManagerNative.java:5140)
04-10 11:53:43.900 25769 25769 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$UncaughtHandler.uncaughtException(RuntimeInit.java:97)
04-10 11:53:43.900 25769 25769 E AndroidRuntime: 	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1068)
04-10 11:53:43.900 25769 25769 E AndroidRuntime: 	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1063)
--- crash end ---
--- brevent start ---
>>> logcat -b main -t '04-10 11:53:42.000' -d -s BreventLoader BreventServer
04-10 11:53:43.181 25758 25758 D BreventLoader: loader path: /data/app/me.piebridge.brevent-1/base.apk
04-10 11:53:43.516 25769 25769 W BreventServer: Can't find Settings.Secure.QS_TILES
04-10 11:53:43.523 25769 25769 I BreventServer: classloader: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/me.piebridge.brevent-1/base.apk"],nativeLibraryDirectories=[/system/lib64, /vendor/lib64, /system/lib64, /vendor/lib64]]]
04-10 11:53:43.524 25769 25769 I BreventServer: Brevent Server 1.0 started
04-10 11:53:43.529 25769 25769 W BreventServer: Can't find Settings.Secure.QS_TILES
04-10 11:53:43.531 25769 25769 I BreventServer: brevent user: 0, uid: 0
04-10 11:53:43.532 25769 25769 I BreventServer: brevent data directory: /data/user_de/0/com.android.shell
04-10 11:53:43.879 25769 25769 I BreventServer: loading brevent list
04-10 11:53:43.883 25769 25769 I BreventServer: load /data/user_de/0/com.android.shell/me.piebridge.brevent.list, size: 103
04-10 11:53:43.883 25769 25769 I BreventServer: loading brevent conf
04-10 11:53:43.891 25769 25769 D BreventServer: Can't dump widgets (ignore)
04-10 11:53:43.895 25769 25769 E BreventServer: Can't dump activities
04-10 11:53:43.895 25769 25769 E BreventServer: android.os.DeadObjectException: Transaction failed on small parcel; remote process probably died
04-10 11:53:43.895 25769 25769 E BreventServer: 	at android.os.BinderProxy.transactNative(Native Method)
04-10 11:53:43.895 25769 25769 E BreventServer: 	at android.os.BinderProxy.transact(Binder.java:615)
04-10 11:53:43.895 25769 25769 E BreventServer: 	at android.os.BinderProxy.dump(Binder.java:631)
04-10 11:53:43.895 25769 25769 E BreventServer: 	at me.piebridge.brevent.server.d.d(HideApi.java:321)
04-10 11:53:43.895 25769 25769 E BreventServer: 	at me.piebridge.brevent.server.BreventServer.<init>(BreventServer.java:217)
04-10 11:53:43.895 25769 25769 E BreventServer: 	at me.piebridge.brevent.server.BreventServer.startBreventServer(BreventServer.java:1524)
04-10 11:53:43.895 25769 25769 E BreventServer: 	at java.lang.reflect.Method.invoke(Native Method)
04-10 11:53:43.895 25769 25769 E BreventServer: 	at me.piebridge.brevent.server.BreventServer.main(BreventServer.java:1582)
04-10 11:53:43.895 25769 25769 E BreventServer: 	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
04-10 11:53:43.895 25769 25769 E BreventServer: 	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:262)
04-10 11:53:43.915 25758 25758 E BreventLoader: worker 25769 exited on signal 9
04-10 11:53:43.915 25758 25758 D BreventLoader: signal arrived, update: 0
04-10 11:53:43.916 25757 25757 D BreventLoader: worker 25758 exited with status 0
--- brevent end ---
```

**Comment by wzhy90** [comment]
好像是MagiskSU的root在enforce下dumpsys package出错了
