### ISSUE TITLE
多次开关【识别非正常“返回”】黑域崩溃

### ISSUE THREAD

**Issue by Vstory** [liudongmiao/Brevent#451]
PS D:\Software\ADB\platform-tools> .\adb -d logcat -d -b crash
04-25 13:17:20.301 11987 11987 F libc    : Fatal signal 11 (SIGSEGV), code 1, fault addr 0x0 in tid 11987 (toybox)
04-25 13:17:20.412   640   640 F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
04-25 13:17:20.412   640   640 F DEBUG   : Build fingerprint: 'Xiaomi/land/land:6.0.1/MMB29M/7.4.24:user/release-keys'
04-25 13:17:20.412   640   640 F DEBUG   : Revision: '0'
04-25 13:17:20.412   640   640 F DEBUG   : ABI: 'arm64'
04-25 13:17:20.412   640   640 F DEBUG   : pid: 11987, tid: 11987, name: toybox  >>> toybox <<<
04-25 13:17:20.413   640   640 F DEBUG   : signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x0
04-25 13:17:20.419   640   640 F DEBUG   :     x0   0000000000000000  x1   0000000000000000  x2   ffffffffffffffff  x3   0000000000000074
04-25 13:17:20.419   640   640 F DEBUG   :     x4   0000000000000074  x5   0000000000000000  x6   0000808080808080  x7   0000000000000000
04-25 13:17:20.419   640   640 F DEBUG   :     x8   000000001bb968f7  x9   fefefefefeff736d  x10  7f7f7f7f7f7f7f7f  x11  0101010101010101
04-25 13:17:20.420   640   640 F DEBUG   :     x12  0000000000000010  x13  0000000000000000  x14  000000559eb713c0  x15  0000000000000f30
04-25 13:17:20.420   640   640 F DEBUG   :     x16  0000007f869abd40  x17  0000007f8691d6a4  x18  000000559eb713e0  x19  0000000000000001
04-25 13:17:20.420   640   640 F DEBUG   :     x20  00000055850e7b24  x21  0000000000000007  x22  0000000000000001  x23  0000000000000007
04-25 13:17:20.420   640   640 F DEBUG   :     x24  000000559eb713d3  x25  0000000000000000  x26  0000000000000000  x27  0000000000000000
04-25 13:17:20.420   640   640 F DEBUG   :     x28  0000005585105d20  x29  0000007fd5840730  x30  0000007f86974994
04-25 13:17:20.420   640   640 F DEBUG   :     sp   0000007fd5840730  pc   0000007f8691d6b4  pstate 0000000040000000
04-25 13:17:20.438   640   640 F DEBUG   :
04-25 13:17:20.438   640   640 F DEBUG   : backtrace:
04-25 13:17:20.438   640   640 F DEBUG   :     #00 pc 000000000001a6b4  /system/lib64/libc.so (strlen+16)
04-25 13:17:20.438   640   640 F DEBUG   :     #01 pc 0000000000071990  /system/lib64/libc.so (__strlen_chk+12)
04-25 13:17:20.438   640   640 F DEBUG   :     #02 pc 000000000000b454  /system/bin/toybox
04-25 13:17:20.438   640   640 F DEBUG   :     #03 pc 0000000000010104  /system/bin/toybox
04-25 13:17:20.438   640   640 F DEBUG   :     #04 pc 000000000000ed14  /system/bin/toybox
04-25 13:17:20.438   640   640 F DEBUG   :     #05 pc 000000000000e8d0  /system/bin/toybox
04-25 13:17:20.438   640   640 F DEBUG   :     #06 pc 000000000000ed14  /system/bin/toybox
04-25 13:17:20.438   640   640 F DEBUG   :     #07 pc 000000000000e8d0  /system/bin/toybox
04-25 13:17:20.438   640   640 F DEBUG   :     #08 pc 000000000000ed50  /system/bin/toybox (main+52)
04-25 13:17:20.438   640   640 F DEBUG   :     #09 pc 000000000001976c  /system/lib64/libc.so (__libc_init+100)
04-25 13:17:20.439   640   640 F DEBUG   :     #10 pc 000000000000a290  /system/bin/toybox
04-25 13:17:20.506   640   640 F DEBUG   :
04-25 13:17:20.506   640   640 F DEBUG   : Tombstone written to: /data/tombstones/tombstone_06
04-25 13:17:21.602 12054 12054 F libc    : Fatal signal 11 (SIGSEGV), code 1, fault addr 0x0 in tid 12054 (toybox)
04-25 13:17:21.706   640   640 F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
04-25 13:17:21.706   640   640 F DEBUG   : Build fingerprint: 'Xiaomi/land/land:6.0.1/MMB29M/7.4.24:user/release-keys'
04-25 13:17:21.706   640   640 F DEBUG   : Revision: '0'
04-25 13:17:21.706   640   640 F DEBUG   : ABI: 'arm64'
04-25 13:17:21.707   640   640 F DEBUG   : pid: 12054, tid: 12054, name: toybox  >>> toybox <<<
04-25 13:17:21.707   640   640 F DEBUG   : signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x0
04-25 13:17:21.710   640   640 F DEBUG   :     x0   0000000000000000  x1   0000000000000000  x2   ffffffffffffffff  x3   0000000000000074
04-25 13:17:21.710   640   640 F DEBUG   :     x4   0000000000000074  x5   0000000000000000  x6   0000808080808080  x7   0000000000000000
04-25 13:17:21.710   640   640 F DEBUG   :     x8   000000005f93c8f7  x9   fefefefefeff736d  x10  7f7f7f7f7f7f7f7f  x11  0101010101010101
04-25 13:17:21.710   640   640 F DEBUG   :     x12  0000000000000010  x13  0000000000000000  x14  00000055cce2d3c0  x15  0000000000000f30
04-25 13:17:21.710   640   640 F DEBUG   :     x16  0000007f78f67d40  x17  0000007f78ed96a4  x18  00000055cce2d3e0  x19  0000000000000001
04-25 13:17:21.710   640   640 F DEBUG   :     x20  0000005593711b24  x21  0000000000000007  x22  0000000000000001  x23  0000000000000007
04-25 13:17:21.710   640   640 F DEBUG   :     x24  00000055cce2d3d3  x25  0000000000000000  x26  0000000000000000  x27  0000000000000000
04-25 13:17:21.710   640   640 F DEBUG   :     x28  000000559372fd20  x29  0000007feeea2d10  x30  0000007f78f30994
04-25 13:17:21.710   640   640 F DEBUG   :     sp   0000007feeea2d10  pc   0000007f78ed96b4  pstate 0000000040000000
04-25 13:17:21.717   640   640 F DEBUG   :
04-25 13:17:21.717   640   640 F DEBUG   : backtrace:
04-25 13:17:21.717   640   640 F DEBUG   :     #00 pc 000000000001a6b4  /system/lib64/libc.so (strlen+16)
04-25 13:17:21.717   640   640 F DEBUG   :     #01 pc 0000000000071990  /system/lib64/libc.so (__strlen_chk+12)
04-25 13:17:21.717   640   640 F DEBUG   :     #02 pc 000000000000b454  /system/bin/toybox
04-25 13:17:21.717   640   640 F DEBUG   :     #03 pc 0000000000010104  /system/bin/toybox
04-25 13:17:21.718   640   640 F DEBUG   :     #04 pc 000000000000ed14  /system/bin/toybox
04-25 13:17:21.718   640   640 F DEBUG   :     #05 pc 000000000000e8d0  /system/bin/toybox
04-25 13:17:21.718   640   640 F DEBUG   :     #06 pc 000000000000ed14  /system/bin/toybox
04-25 13:17:21.718   640   640 F DEBUG   :     #07 pc 000000000000e8d0  /system/bin/toybox
04-25 13:17:21.718   640   640 F DEBUG   :     #08 pc 000000000000ed50  /system/bin/toybox (main+52)
04-25 13:17:21.718   640   640 F DEBUG   :     #09 pc 000000000001976c  /system/lib64/libc.so (__libc_init+100)
04-25 13:17:21.718   640   640 F DEBUG   :     #10 pc 000000000000a290  /system/bin/toybox
04-25 13:17:21.798   640   640 F DEBUG   :
04-25 13:17:21.798   640   640 F DEBUG   : Tombstone written to: /data/tombstones/tombstone_07
04-25 21:04:31.581 15547 15547 F libc    : Fatal signal 13 (SIGPIPE), code 0 in tid 15547 (sh)
04-25 21:04:31.688   640   640 F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
04-25 21:04:31.689   640   640 F DEBUG   : Build fingerprint: 'Xiaomi/land/land:6.0.1/MMB29M/7.4.24:user/release-keys'
04-25 21:04:31.689   640   640 F DEBUG   : Revision: '0'
04-25 21:04:31.689   640   640 F DEBUG   : ABI: 'arm64'
04-25 21:04:31.689   640   640 F DEBUG   : pid: 15547, tid: 15547, name: sh  >>> sh <<<
04-25 21:04:31.689   640   640 F DEBUG   : signal 13 (SIGPIPE), code 0 (SI_USER), fault addr --------
04-25 21:04:31.691   640   640 F DEBUG   :     x0   ffffffffffffffe0  x1   000000556d3a77e8  x2   0000000000000007  x3   000000556d3a77ee
04-25 21:04:31.691   640   640 F DEBUG   :     x4   0000000000000000  x5   0000000000000001  x6   000000556d3a7868  x7   00000000000000e0
04-25 21:04:31.691   640   640 F DEBUG   :     x8   0000000000000040  x9   0000000000051450  x10  0000000010051450  x11  0000000000000080
04-25 21:04:31.691   640   640 F DEBUG   :     x12  000000556d3a7868  x13  0000005557e3a000  x14  0000005557e3a000  x15  000000000000000a
04-25 21:04:31.691   640   640 F DEBUG   :     x16  0000005557e76b50  x17  0000007f91658d2c  x18  00000000ffffffff  x19  0000000000000007
04-25 21:04:31.691   640   640 F DEBUG   :     x20  000000556d3a77e8  x21  0000000000000000  x22  0000000000000000  x23  0000000000000003
04-25 21:04:31.691   640   640 F DEBUG   :     x24  000000556d3a77ef  x25  0000000000000003  x26  0000000000000001  x27  0000000000000007
04-25 21:04:31.691   640   640 F DEBUG   :     x28  0000000000000007  x29  0000007ff6f58e60  x30  0000005557e3ab68
04-25 21:04:31.691   640   640 F DEBUG   :     sp   0000007ff6f58e60  pc   0000007f91658d34  pstate 0000000020000000
04-25 21:04:31.701   640   640 F DEBUG   :
04-25 21:04:31.701   640   640 F DEBUG   : backtrace:
04-25 21:04:31.701   640   640 F DEBUG   :     #00 pc 000000000006ad34  /system/lib64/libc.so (write+8)
04-25 21:04:31.701   640   640 F DEBUG   :     #01 pc 0000000000019b64  /system/bin/sh
04-25 21:04:31.702   640   640 F DEBUG   :     #02 pc 000000000001522c  /system/bin/sh
04-25 21:04:31.702   640   640 F DEBUG   :     #03 pc 0000000000017ba4  /system/bin/sh
04-25 21:04:31.702   640   640 F DEBUG   :     #04 pc 0000000000016edc  /system/bin/sh
04-25 21:04:31.702   640   640 F DEBUG   :     #05 pc 000000000002a2d4  /system/bin/sh
04-25 21:04:31.702   640   640 F DEBUG   :     #06 pc 000000000000629c  /system/bin/sh (main+1848)
04-25 21:04:31.702   640   640 F DEBUG   :     #07 pc 000000000001976c  /system/lib64/libc.so (__libc_init+100)
04-25 21:04:31.702   640   640 F DEBUG   :     #08 pc 0000000000006860  /system/bin/sh
04-25 21:04:31.780   640   640 F DEBUG   :
04-25 21:04:31.780   640   640 F DEBUG   : Tombstone written to: /data/tombstones/tombstone_08
04-25 21:24:33.020 28840 28876 E AndroidRuntime: FATAL EXCEPTION: Brevent
04-25 21:24:33.020 28840 28876 E AndroidRuntime: Process: me.piebridge.brevent, PID: 28840
04-25 21:24:33.020 28840 28876 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.os.Handler.sendEmptyMessage(int)' on a null object reference
04-25 21:24:33.020 28840 28876 E AndroidRuntime:        at me.piebridge.brevent.ui.BreventActivity.a(BreventActivity.java:848)
04-25 21:24:33.020 28840 28876 E AndroidRuntime:        at me.piebridge.brevent.ui.BreventActivity.a(BreventActivity.java:764)
04-25 21:24:33.020 28840 28876 E AndroidRuntime:        at me.piebridge.brevent.ui.a.handleMessage(AppsActivityHandler.java:77)
04-25 21:24:33.020 28840 28876 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:102)
04-25 21:24:33.020 28840 28876 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:154)
04-25 21:24:33.020 28840 28876 E AndroidRuntime:        at android.os.HandlerThread.run(HandlerThread.java:61)
PS D:\Software\ADB\platform-tools>

机型：Redmi 3X
MIUI:MIUI8 7.4.24

**Comment by Vstory** [comment]
PS D:\Software\ADB\platform-tools> .\adb -d logcat -d -b crash
04-25 13:17:20.301 11987 11987 F libc    : Fatal signal 11 (SIGSEGV), code 1, fault addr 0x0 in tid 11987 (toybox)
04-25 13:17:20.412   640   640 F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
04-25 13:17:20.412   640   640 F DEBUG   : Build fingerprint: 'Xiaomi/land/land:6.0.1/MMB29M/7.4.24:user/release-keys'
04-25 13:17:20.412   640   640 F DEBUG   : Revision: '0'
04-25 13:17:20.412   640   640 F DEBUG   : ABI: 'arm64'
04-25 13:17:20.412   640   640 F DEBUG   : pid: 11987, tid: 11987, name: toybox  >>> toybox <<<
04-25 13:17:20.413   640   640 F DEBUG   : signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x0
04-25 13:17:20.419   640   640 F DEBUG   :     x0   0000000000000000  x1   0000000000000000  x2   ffffffffffffffff  x3   0000000000000074
04-25 13:17:20.419   640   640 F DEBUG   :     x4   0000000000000074  x5   0000000000000000  x6   0000808080808080  x7   0000000000000000
04-25 13:17:20.419   640   640 F DEBUG   :     x8   000000001bb968f7  x9   fefefefefeff736d  x10  7f7f7f7f7f7f7f7f  x11  0101010101010101
04-25 13:17:20.420   640   640 F DEBUG   :     x12  0000000000000010  x13  0000000000000000  x14  000000559eb713c0  x15  0000000000000f30
04-25 13:17:20.420   640   640 F DEBUG   :     x16  0000007f869abd40  x17  0000007f8691d6a4  x18  000000559eb713e0  x19  0000000000000001
04-25 13:17:20.420   640   640 F DEBUG   :     x20  00000055850e7b24  x21  0000000000000007  x22  0000000000000001  x23  0000000000000007
04-25 13:17:20.420   640   640 F DEBUG   :     x24  000000559eb713d3  x25  0000000000000000  x26  0000000000000000  x27  0000000000000000
04-25 13:17:20.420   640   640 F DEBUG   :     x28  0000005585105d20  x29  0000007fd5840730  x30  0000007f86974994
04-25 13:17:20.420   640   640 F DEBUG   :     sp   0000007fd5840730  pc   0000007f8691d6b4  pstate 0000000040000000
04-25 13:17:20.438   640   640 F DEBUG   :
04-25 13:17:20.438   640   640 F DEBUG   : backtrace:
04-25 13:17:20.438   640   640 F DEBUG   :     #00 pc 000000000001a6b4  /system/lib64/libc.so (strlen+16)
04-25 13:17:20.438   640   640 F DEBUG   :     #01 pc 0000000000071990  /system/lib64/libc.so (__strlen_chk+12)
04-25 13:17:20.438   640   640 F DEBUG   :     #02 pc 000000000000b454  /system/bin/toybox
04-25 13:17:20.438   640   640 F DEBUG   :     #03 pc 0000000000010104  /system/bin/toybox
04-25 13:17:20.438   640   640 F DEBUG   :     #04 pc 000000000000ed14  /system/bin/toybox
04-25 13:17:20.438   640   640 F DEBUG   :     #05 pc 000000000000e8d0  /system/bin/toybox
04-25 13:17:20.438   640   640 F DEBUG   :     #06 pc 000000000000ed14  /system/bin/toybox
04-25 13:17:20.438   640   640 F DEBUG   :     #07 pc 000000000000e8d0  /system/bin/toybox
04-25 13:17:20.438   640   640 F DEBUG   :     #08 pc 000000000000ed50  /system/bin/toybox (main+52)
04-25 13:17:20.438   640   640 F DEBUG   :     #09 pc 000000000001976c  /system/lib64/libc.so (__libc_init+100)
04-25 13:17:20.439   640   640 F DEBUG   :     #10 pc 000000000000a290  /system/bin/toybox
04-25 13:17:20.506   640   640 F DEBUG   :
04-25 13:17:20.506   640   640 F DEBUG   : Tombstone written to: /data/tombstones/tombstone_06
04-25 13:17:21.602 12054 12054 F libc    : Fatal signal 11 (SIGSEGV), code 1, fault addr 0x0 in tid 12054 (toybox)
04-25 13:17:21.706   640   640 F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
04-25 13:17:21.706   640   640 F DEBUG   : Build fingerprint: 'Xiaomi/land/land:6.0.1/MMB29M/7.4.24:user/release-keys'
04-25 13:17:21.706   640   640 F DEBUG   : Revision: '0'
04-25 13:17:21.706   640   640 F DEBUG   : ABI: 'arm64'
04-25 13:17:21.707   640   640 F DEBUG   : pid: 12054, tid: 12054, name: toybox  >>> toybox <<<
04-25 13:17:21.707   640   640 F DEBUG   : signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x0
04-25 13:17:21.710   640   640 F DEBUG   :     x0   0000000000000000  x1   0000000000000000  x2   ffffffffffffffff  x3   0000000000000074
04-25 13:17:21.710   640   640 F DEBUG   :     x4   0000000000000074  x5   0000000000000000  x6   0000808080808080  x7   0000000000000000
04-25 13:17:21.710   640   640 F DEBUG   :     x8   000000005f93c8f7  x9   fefefefefeff736d  x10  7f7f7f7f7f7f7f7f  x11  0101010101010101
04-25 13:17:21.710   640   640 F DEBUG   :     x12  0000000000000010  x13  0000000000000000  x14  00000055cce2d3c0  x15  0000000000000f30
04-25 13:17:21.710   640   640 F DEBUG   :     x16  0000007f78f67d40  x17  0000007f78ed96a4  x18  00000055cce2d3e0  x19  0000000000000001
04-25 13:17:21.710   640   640 F DEBUG   :     x20  0000005593711b24  x21  0000000000000007  x22  0000000000000001  x23  0000000000000007
04-25 13:17:21.710   640   640 F DEBUG   :     x24  00000055cce2d3d3  x25  0000000000000000  x26  0000000000000000  x27  0000000000000000
04-25 13:17:21.710   640   640 F DEBUG   :     x28  000000559372fd20  x29  0000007feeea2d10  x30  0000007f78f30994
04-25 13:17:21.710   640   640 F DEBUG   :     sp   0000007feeea2d10  pc   0000007f78ed96b4  pstate 0000000040000000
04-25 13:17:21.717   640   640 F DEBUG   :
04-25 13:17:21.717   640   640 F DEBUG   : backtrace:
04-25 13:17:21.717   640   640 F DEBUG   :     #00 pc 000000000001a6b4  /system/lib64/libc.so (strlen+16)
04-25 13:17:21.717   640   640 F DEBUG   :     #01 pc 0000000000071990  /system/lib64/libc.so (__strlen_chk+12)
04-25 13:17:21.717   640   640 F DEBUG   :     #02 pc 000000000000b454  /system/bin/toybox
04-25 13:17:21.717   640   640 F DEBUG   :     #03 pc 0000000000010104  /system/bin/toybox
04-25 13:17:21.718   640   640 F DEBUG   :     #04 pc 000000000000ed14  /system/bin/toybox
04-25 13:17:21.718   640   640 F DEBUG   :     #05 pc 000000000000e8d0  /system/bin/toybox
04-25 13:17:21.718   640   640 F DEBUG   :     #06 pc 000000000000ed14  /system/bin/toybox
04-25 13:17:21.718   640   640 F DEBUG   :     #07 pc 000000000000e8d0  /system/bin/toybox
04-25 13:17:21.718   640   640 F DEBUG   :     #08 pc 000000000000ed50  /system/bin/toybox (main+52)
04-25 13:17:21.718   640   640 F DEBUG   :     #09 pc 000000000001976c  /system/lib64/libc.so (__libc_init+100)
04-25 13:17:21.718   640   640 F DEBUG   :     #10 pc 000000000000a290  /system/bin/toybox
04-25 13:17:21.798   640   640 F DEBUG   :
04-25 13:17:21.798   640   640 F DEBUG   : Tombstone written to: /data/tombstones/tombstone_07
04-25 21:04:31.581 15547 15547 F libc    : Fatal signal 13 (SIGPIPE), code 0 in tid 15547 (sh)
04-25 21:04:31.688   640   640 F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
04-25 21:04:31.689   640   640 F DEBUG   : Build fingerprint: 'Xiaomi/land/land:6.0.1/MMB29M/7.4.24:user/release-keys'
04-25 21:04:31.689   640   640 F DEBUG   : Revision: '0'
04-25 21:04:31.689   640   640 F DEBUG   : ABI: 'arm64'
04-25 21:04:31.689   640   640 F DEBUG   : pid: 15547, tid: 15547, name: sh  >>> sh <<<
04-25 21:04:31.689   640   640 F DEBUG   : signal 13 (SIGPIPE), code 0 (SI_USER), fault addr --------
04-25 21:04:31.691   640   640 F DEBUG   :     x0   ffffffffffffffe0  x1   000000556d3a77e8  x2   0000000000000007  x3   000000556d3a77ee
04-25 21:04:31.691   640   640 F DEBUG   :     x4   0000000000000000  x5   0000000000000001  x6   000000556d3a7868  x7   00000000000000e0
04-25 21:04:31.691   640   640 F DEBUG   :     x8   0000000000000040  x9   0000000000051450  x10  0000000010051450  x11  0000000000000080
04-25 21:04:31.691   640   640 F DEBUG   :     x12  000000556d3a7868  x13  0000005557e3a000  x14  0000005557e3a000  x15  000000000000000a
04-25 21:04:31.691   640   640 F DEBUG   :     x16  0000005557e76b50  x17  0000007f91658d2c  x18  00000000ffffffff  x19  0000000000000007
04-25 21:04:31.691   640   640 F DEBUG   :     x20  000000556d3a77e8  x21  0000000000000000  x22  0000000000000000  x23  0000000000000003
04-25 21:04:31.691   640   640 F DEBUG   :     x24  000000556d3a77ef  x25  0000000000000003  x26  0000000000000001  x27  0000000000000007
04-25 21:04:31.691   640   640 F DEBUG   :     x28  0000000000000007  x29  0000007ff6f58e60  x30  0000005557e3ab68
04-25 21:04:31.691   640   640 F DEBUG   :     sp   0000007ff6f58e60  pc   0000007f91658d34  pstate 0000000020000000
04-25 21:04:31.701   640   640 F DEBUG   :
04-25 21:04:31.701   640   640 F DEBUG   : backtrace:
04-25 21:04:31.701   640   640 F DEBUG   :     #00 pc 000000000006ad34  /system/lib64/libc.so (write+8)
04-25 21:04:31.701   640   640 F DEBUG   :     #01 pc 0000000000019b64  /system/bin/sh
04-25 21:04:31.702   640   640 F DEBUG   :     #02 pc 000000000001522c  /system/bin/sh
04-25 21:04:31.702   640   640 F DEBUG   :     #03 pc 0000000000017ba4  /system/bin/sh
04-25 21:04:31.702   640   640 F DEBUG   :     #04 pc 0000000000016edc  /system/bin/sh
04-25 21:04:31.702   640   640 F DEBUG   :     #05 pc 000000000002a2d4  /system/bin/sh
04-25 21:04:31.702   640   640 F DEBUG   :     #06 pc 000000000000629c  /system/bin/sh (main+1848)
04-25 21:04:31.702   640   640 F DEBUG   :     #07 pc 000000000001976c  /system/lib64/libc.so (__libc_init+100)
04-25 21:04:31.702   640   640 F DEBUG   :     #08 pc 0000000000006860  /system/bin/sh
04-25 21:04:31.780   640   640 F DEBUG   :
04-25 21:04:31.780   640   640 F DEBUG   : Tombstone written to: /data/tombstones/tombstone_08
04-25 21:24:33.020 28840 28876 E AndroidRuntime: FATAL EXCEPTION: Brevent
04-25 21:24:33.020 28840 28876 E AndroidRuntime: Process: me.piebridge.brevent, PID: 28840
04-25 21:24:33.020 28840 28876 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.os.Handler.sendEmptyMessage(int)' on a null object reference
04-25 21:24:33.020 28840 28876 E AndroidRuntime:        at me.piebridge.brevent.ui.BreventActivity.a(BreventActivity.java:848)
04-25 21:24:33.020 28840 28876 E AndroidRuntime:        at me.piebridge.brevent.ui.BreventActivity.a(BreventActivity.java:764)
04-25 21:24:33.020 28840 28876 E AndroidRuntime:        at me.piebridge.brevent.ui.a.handleMessage(AppsActivityHandler.java:77)
04-25 21:24:33.020 28840 28876 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:102)
04-25 21:24:33.020 28840 28876 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:154)
04-25 21:24:33.020 28840 28876 E AndroidRuntime:        at android.os.HandlerThread.run(HandlerThread.java:61)
04-25 21:35:46.820 31441 31477 E AndroidRuntime: FATAL EXCEPTION: Brevent
04-25 21:35:46.820 31441 31477 E AndroidRuntime: Process: me.piebridge.brevent, PID: 31441
04-25 21:35:46.820 31441 31477 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.os.Handler.sendEmptyMessage(int)' on a null object reference
04-25 21:35:46.820 31441 31477 E AndroidRuntime:        at me.piebridge.brevent.ui.BreventActivity.a(BreventActivity.java:848)
04-25 21:35:46.820 31441 31477 E AndroidRuntime:        at me.piebridge.brevent.ui.BreventActivity.a(BreventActivity.java:764)
04-25 21:35:46.820 31441 31477 E AndroidRuntime:        at me.piebridge.brevent.ui.a.handleMessage(AppsActivityHandler.java:77)
04-25 21:35:46.820 31441 31477 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:102)
04-25 21:35:46.820 31441 31477 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:154)
04-25 21:35:46.820 31441 31477 E AndroidRuntime:        at android.os.HandlerThread.run(HandlerThread.java:61)
PS D:\Software\ADB\platform-tools>
