### ISSUE TITLE
1.1.2的测试版，这是怎么回事，而且好像打开谷歌商店会特别慢

### ISSUE THREAD

**Issue by huahua2017** [liudongmiao/Brevent#482]
java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
	at android.app.FragmentManagerImpl.checkStateLoss(FragmentManager.java:1356)
	at android.app.FragmentManagerImpl.enqueueAction(FragmentManager.java:1374)
	at android.app.BackStackRecord.commitInternal(BackStackRecord.java:750)
	at android.app.BackStackRecord.commit(BackStackRecord.java:726)
	at android.app.DialogFragment.dismissInternal(DialogFragment.java:292)
	at android.app.DialogFragment.dismiss(DialogFragment.java:258)
	at me.piebridge.brevent.ui.BreventActivity.o(BreventActivity.java:352)
	at me.piebridge.brevent.ui.BreventActivity.c(BreventActivity.java:338)
	at me.piebridge.brevent.ui.BreventActivity.a(BreventActivity.java:283)
	at me.piebridge.brevent.ui.b.handleMessage(AppsActivityUIHandler.java:44)
	at android.os.Handler.dispatchMessage(Handler.java:111)
	at android.os.Looper.loop(Looper.java:194)
	at android.app.ActivityThread.main(ActivityThread.java:5556)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:967)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:762)
	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:102)

**Comment by liudongmiao** [comment]
我个人自动忽略带 xposed 的异常栈，也就是，不保证与 xposed 兼容。

**Comment by huahua2017** [comment]
好吧，谢谢啦，我自己在琢磨琢磨
