### ISSUE TITLE
cannot listen port - 网络权限变种

### ISSUE THREAD

**Issue by pandada8** [liudongmiao/Brevent#87]
小米 4c, CyanogenMod 13.1
```
~ ❯❯❯ adb shell /data/app/me.piebridge.brevent-1/lib/arm/libbootstrap.so
please run with 'su shell /data/app/me.piebridge.brevent-1/lib/arm/libbootstrap.so'
~ ❯❯❯ adb shell "su shell /data/app/me.piebridge.brevent-1/lib/arm/libbootstrap.so"
checking.............
cannot listen port, please report bug to https://github.com/liudongmiao/Brevent/issues with log below
--- crash start ---
02-19 22:10:21.530 16906 16929 E AndroidRuntime: *** FATAL EXCEPTION IN SYSTEM PROCESS: Thread-11
02-19 22:10:21.530 16906 16929 E AndroidRuntime: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
02-19 22:10:21.530 16906 16929 E AndroidRuntime: 	at me.piebridge.brevent.loader.Brevent.run(Brevent.java:60)
02-19 22:10:21.530 16906 16929 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:818)
02-19 22:10:21.530 16906 16929 E AndroidRuntime: Caused by: java.lang.reflect.InvocationTargetException
02-19 22:10:21.530 16906 16929 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
02-19 22:10:21.530 16906 16929 E AndroidRuntime: 	at me.piebridge.brevent.loader.Brevent.run(Brevent.java:57)
02-19 22:10:21.530 16906 16929 E AndroidRuntime: 	... 1 more
02-19 22:10:21.530 16906 16929 E AndroidRuntime: Caused by: java.net.SocketException: socket failed: EACCES (Permission denied)
02-19 22:10:21.530 16906 16929 E AndroidRuntime: 	at libcore.io.IoBridge.socket(IoBridge.java:619)
02-19 22:10:21.530 16906 16929 E AndroidRuntime: 	at java.net.PlainSocketImpl.create(PlainSocketImpl.java:198)
02-19 22:10:21.530 16906 16929 E AndroidRuntime: 	at java.net.PlainServerSocketImpl.create(PlainServerSocketImpl.java:38)
02-19 22:10:21.530 16906 16929 E AndroidRuntime: 	at java.net.ServerSocket.<init>(ServerSocket.java:104)
02-19 22:10:21.530 16906 16929 E AndroidRuntime: 	at me.piebridge.brevent.server.BreventServer.main(BreventServer.java:849)
02-19 22:10:21.530 16906 16929 E AndroidRuntime: 	... 3 more
02-19 22:10:21.530 16906 16929 E AndroidRuntime: Caused by: android.system.ErrnoException: socket failed: EACCES (Permission denied)
02-19 22:10:21.530 16906 16929 E AndroidRuntime: 	at libcore.io.Posix.socket(Native Method)
02-19 22:10:21.530 16906 16929 E AndroidRuntime: 	at libcore.io.BlockGuardOs.socket(BlockGuardOs.java:282)
02-19 22:10:21.530 16906 16929 E AndroidRuntime: 	at libcore.io.IoBridge.socket(IoBridge.java:604)
02-19 22:10:21.530 16906 16929 E AndroidRuntime: 	... 7 more
02-19 22:10:21.534 16906 16929 E AndroidRuntime: Error reporting crash
02-19 22:10:21.534 16906 16929 E AndroidRuntime: java.lang.RuntimeException: Bad file descriptor
02-19 22:10:21.534 16906 16929 E AndroidRuntime: 	at android.os.BinderProxy.transactNative(Native Method)
02-19 22:10:21.534 16906 16929 E AndroidRuntime: 	at android.os.BinderProxy.transact(Binder.java:503)
02-19 22:10:21.534 16906 16929 E AndroidRuntime: 	at android.app.ActivityManagerProxy.handleApplicationCrash(ActivityManagerNative.java:4473)
02-19 22:10:21.534 16906 16929 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$UncaughtHandler.uncaughtException(RuntimeInit.java:95)
02-19 22:10:21.534 16906 16929 E AndroidRuntime: 	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:693)
02-19 22:10:21.534 16906 16929 E AndroidRuntime: 	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:690)
02-19 22:12:29.907 17139 17158 E AndroidRuntime: *** FATAL EXCEPTION IN SYSTEM PROCESS: Thread-10
02-19 22:12:29.907 17139 17158 E AndroidRuntime: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
02-19 22:12:29.907 17139 17158 E AndroidRuntime: 	at me.piebridge.brevent.loader.Brevent.run(Brevent.java:60)
02-19 22:12:29.907 17139 17158 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:818)
02-19 22:12:29.907 17139 17158 E AndroidRuntime: Caused by: java.lang.reflect.InvocationTargetException
02-19 22:12:29.907 17139 17158 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
02-19 22:12:29.907 17139 17158 E AndroidRuntime: 	at me.piebridge.brevent.loader.Brevent.run(Brevent.java:57)
02-19 22:12:29.907 17139 17158 E AndroidRuntime: 	... 1 more
02-19 22:12:29.907 17139 17158 E AndroidRuntime: Caused by: java.net.SocketException: socket failed: EACCES (Permission denied)
02-19 22:12:29.907 17139 17158 E AndroidRuntime: 	at libcore.io.IoBridge.socket(IoBridge.java:619)
02-19 22:12:29.907 17139 17158 E AndroidRuntime: 	at java.net.PlainSocketImpl.create(PlainSocketImpl.java:198)
02-19 22:12:29.907 17139 17158 E AndroidRuntime: 	at java.net.PlainServerSocketImpl.create(PlainServerSocketImpl.java:38)
02-19 22:12:29.907 17139 17158 E AndroidRuntime: 	at java.net.ServerSocket.<init>(ServerSocket.java:104)
02-19 22:12:29.907 17139 17158 E AndroidRuntime: 	at me.piebridge.brevent.server.BreventServer.main(BreventServer.java:849)
02-19 22:12:29.907 17139 17158 E AndroidRuntime: 	... 3 more
02-19 22:12:29.907 17139 17158 E AndroidRuntime: Caused by: android.system.ErrnoException: socket failed: EACCES (Permission denied)
02-19 22:12:29.907 17139 17158 E AndroidRuntime: 	at libcore.io.Posix.socket(Native Method)
02-19 22:12:29.907 17139 17158 E AndroidRuntime: 	at libcore.io.BlockGuardOs.socket(BlockGuardOs.java:282)
02-19 22:12:29.907 17139 17158 E AndroidRuntime: 	at libcore.io.IoBridge.socket(IoBridge.java:604)
02-19 22:12:29.907 17139 17158 E AndroidRuntime: 	... 7 more
02-19 22:12:29.908 17139 17158 E AndroidRuntime: Error reporting crash
02-19 22:12:29.908 17139 17158 E AndroidRuntime: java.lang.RuntimeException: Bad file descriptor
02-19 22:12:29.908 17139 17158 E AndroidRuntime: 	at android.os.BinderProxy.transactNative(Native Method)
02-19 22:12:29.908 17139 17158 E AndroidRuntime: 	at android.os.BinderProxy.transact(Binder.java:503)
02-19 22:12:29.908 17139 17158 E AndroidRuntime: 	at android.app.ActivityManagerProxy.handleApplicationCrash(ActivityManagerNative.java:4473)
02-19 22:12:29.908 17139 17158 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$UncaughtHandler.uncaughtException(RuntimeInit.java:95)
02-19 22:12:29.908 17139 17158 E AndroidRuntime: 	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:693)
02-19 22:12:29.908 17139 17158 E AndroidRuntime: 	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:690)
--- crash end ---
--- brevent start ---
02-19 22:10:20.895 16906 16906 D BreventLoader: lib: /data/user/0/com.android.shell/brevent, loader: /data/user/0/com.android.shell/brevent/libloader.so
02-19 22:10:20.966 16906 16929 D BreventServer: Brevent Server 0.7 started
02-19 22:10:20.986 16906 16929 D BreventServer: brevent user: 0, uid: 2000
02-19 22:10:20.987 16906 16929 D BreventServer: brevent data directory: /data/user/0/com.android.shell
02-19 22:10:21.045 16906 16929 D BreventServer: loaded brevent list
02-19 22:10:21.045 16906 16929 D BreventServer: loaded brevent conf
02-19 22:10:21.264 16906 16929 D BreventServer: checking
02-19 22:10:21.512 16906 16929 I BreventServer: power_screen_state, tag: 2728, event: 7
02-19 22:10:21.513 16906 16929 I BreventServer: notification_cancel_all, tag: 2752, event: 6
02-19 22:10:21.515 16906 16929 I BreventServer: am_new_intent, tag: 30003, event: 2
02-19 22:10:21.516 16906 16929 I BreventServer: am_pause_activity, tag: 30013, event: 3
02-19 22:10:21.517 16906 16929 I BreventServer: am_proc_start, tag: 30014, event: 4
02-19 22:10:21.518 16906 16929 I BreventServer: am_switch_user, tag: 30041, event: 5
02-19 22:10:21.518 16906 16929 I BreventServer: am_focused_activity, tag: 30043, event: 1
02-19 22:10:21.529 16906 16929 D BreventLoader: Can't run brevent server
02-19 22:10:21.529 16906 16929 D BreventLoader: java.lang.reflect.InvocationTargetException
02-19 22:10:21.529 16906 16929 D BreventLoader: 	at java.lang.reflect.Method.invoke(Native Method)
02-19 22:10:21.529 16906 16929 D BreventLoader: 	at me.piebridge.brevent.loader.Brevent.run(Brevent.java:57)
02-19 22:10:21.529 16906 16929 D BreventLoader: 	at java.lang.Thread.run(Thread.java:818)
02-19 22:10:21.529 16906 16929 D BreventLoader: Caused by: java.net.SocketException: socket failed: EACCES (Permission denied)
02-19 22:10:21.529 16906 16929 D BreventLoader: 	at libcore.io.IoBridge.socket(IoBridge.java:619)
02-19 22:10:21.529 16906 16929 D BreventLoader: 	at java.net.PlainSocketImpl.create(PlainSocketImpl.java:198)
02-19 22:10:21.529 16906 16929 D BreventLoader: 	at java.net.PlainServerSocketImpl.create(PlainServerSocketImpl.java:38)
02-19 22:10:21.529 16906 16929 D BreventLoader: 	at java.net.ServerSocket.<init>(ServerSocket.java:104)
02-19 22:10:21.529 16906 16929 D BreventLoader: 	at me.piebridge.brevent.server.BreventServer.main(BreventServer.java:849)
02-19 22:10:21.529 16906 16929 D BreventLoader: 	... 3 more
02-19 22:10:21.529 16906 16929 D BreventLoader: Caused by: android.system.ErrnoException: socket failed: EACCES (Permission denied)
02-19 22:10:21.529 16906 16929 D BreventLoader: 	at libcore.io.Posix.socket(Native Method)
02-19 22:10:21.529 16906 16929 D BreventLoader: 	at libcore.io.BlockGuardOs.socket(BlockGuardOs.java:282)
02-19 22:10:21.529 16906 16929 D BreventLoader: 	at libcore.io.IoBridge.socket(IoBridge.java:604)
02-19 22:10:21.529 16906 16929 D BreventLoader: 	... 7 more
02-19 22:10:21.529 16906 16906 D BreventLoader: Brevent Server quit in 30 seconds, quit
02-19 22:12:29.316 17139 17139 D BreventLoader: lib: /data/user/0/com.android.shell/brevent, loader: /data/user/0/com.android.shell/brevent/libloader.so
02-19 22:12:29.379 17139 17158 D BreventServer: Brevent Server 0.7 started
02-19 22:12:29.393 17139 17158 D BreventServer: brevent user: 0, uid: 2000
02-19 22:12:29.395 17139 17158 D BreventServer: brevent data directory: /data/user/0/com.android.shell
02-19 22:12:29.455 17139 17158 D BreventServer: loaded brevent list
02-19 22:12:29.456 17139 17158 D BreventServer: loaded brevent conf
02-19 22:12:29.662 17139 17158 D BreventServer: checking
02-19 22:12:29.890 17139 17158 I BreventServer: power_screen_state, tag: 2728, event: 7
02-19 22:12:29.891 17139 17158 I BreventServer: notification_cancel_all, tag: 2752, event: 6
02-19 22:12:29.894 17139 17158 I BreventServer: am_new_intent, tag: 30003, event: 2
02-19 22:12:29.895 17139 17158 I BreventServer: am_pause_activity, tag: 30013, event: 3
02-19 22:12:29.895 17139 17158 I BreventServer: am_proc_start, tag: 30014, event: 4
02-19 22:12:29.897 17139 17158 I BreventServer: am_switch_user, tag: 30041, event: 5
02-19 22:12:29.897 17139 17158 I BreventServer: am_focused_activity, tag: 30043, event: 1
02-19 22:12:29.906 17139 17158 D BreventLoader: Can't run brevent server
02-19 22:12:29.906 17139 17158 D BreventLoader: java.lang.reflect.InvocationTargetException
02-19 22:12:29.906 17139 17158 D BreventLoader: 	at java.lang.reflect.Method.invoke(Native Method)
02-19 22:12:29.906 17139 17158 D BreventLoader: 	at me.piebridge.brevent.loader.Brevent.run(Brevent.java:57)
02-19 22:12:29.906 17139 17158 D BreventLoader: 	at java.lang.Thread.run(Thread.java:818)
02-19 22:12:29.906 17139 17158 D BreventLoader: Caused by: java.net.SocketException: socket failed: EACCES (Permission denied)
02-19 22:12:29.906 17139 17158 D BreventLoader: 	at libcore.io.IoBridge.socket(IoBridge.java:619)
02-19 22:12:29.906 17139 17158 D BreventLoader: 	at java.net.PlainSocketImpl.create(PlainSocketImpl.java:198)
02-19 22:12:29.906 17139 17158 D BreventLoader: 	at java.net.PlainServerSocketImpl.create(PlainServerSocketImpl.java:38)
02-19 22:12:29.906 17139 17158 D BreventLoader: 	at java.net.ServerSocket.<init>(ServerSocket.java:104)
02-19 22:12:29.906 17139 17158 D BreventLoader: 	at me.piebridge.brevent.server.BreventServer.main(BreventServer.java:849)
02-19 22:12:29.906 17139 17158 D BreventLoader: 	... 3 more
02-19 22:12:29.906 17139 17158 D BreventLoader: Caused by: android.system.ErrnoException: socket failed: EACCES (Permission denied)
02-19 22:12:29.906 17139 17158 D BreventLoader: 	at libcore.io.Posix.socket(Native Method)
02-19 22:12:29.906 17139 17158 D BreventLoader: 	at libcore.io.BlockGuardOs.socket(BlockGuardOs.java:282)
02-19 22:12:29.906 17139 17158 D BreventLoader: 	at libcore.io.IoBridge.socket(IoBridge.java:604)
02-19 22:12:29.906 17139 17158 D BreventLoader: 	... 7 more
02-19 22:12:29.906 17139 17139 D BreventLoader: Brevent Server quit in 30 seconds, quit
--- brevent end ---
cannot listen port, please report bug to https://github.com/liudongmiao/Brevent/issues with log above
```

**Comment by liudongmiao** [comment]
没有网络权限，同 #50, #72, #73, #89 ，但是，属于另一个变种。

请尝试设置一下 ROM，执行 `adb shell` 以后，不要给 root 权限。

**Comment by pandada8** [comment]
很僵啊 shell 这个用户根本没有网络权限
不是很熟安卓，有啥解决的方案么，或者说有啥办法可以给网络的权限吗

**Comment by liudongmiao** [comment]
10 天内没继续反馈，关闭。
