### ISSUE TITLE
java.net.SocketException: Permission denied

### ISSUE THREAD

**Issue by simonsmh** [liudongmiao/Brevent#89]
```
build.board: QC_Reference_Phone
build.bootloader: unknown
build.brand: OnePlus
build.cpu_abi: arm64-v8a
build.cpu_abi2: 
build.device: OnePlus3
build.display: ONEPLUS A3000_16_170208
build.fingerprint: OnePlus/OnePlus3/OnePlus3:7.0/NRD90M/01122125:user/release-keys
build.hardware: qcom
build.host: ubuntu-64
build.id: NRD90M
build.manufacturer: OnePlus
build.model: ONEPLUS A3000
build.product: OnePlus3
build.radio: unknown
build.serial: 5dc60b19
build.tags: release-keys
build.time: 1486547347000
build.type: user
build.user: OnePlus
version.codename: REL
version.incremental: 15
version.release: 7.0
version.sdk_int: 24

02-20 00:57:29.543 E/System  (20605): Unable to open zip file: /data/app/me.piebridge.brevent-1/lib/arm/libloader.so
02-20 00:57:29.550 D/AndroidRuntime(20605): Calling main entry me.piebridge.brevent.loader.Brevent
02-20 00:57:29.556 D/BreventLoader(20605): lib: /data/user_de/0/com.android.shell/brevent, loader: /data/user_de/0/com.android.shell/brevent/libloader.so
02-20 00:57:29.587 D/BreventServer(20605): Brevent Server 0.7 started
02-20 00:57:29.595 D/BreventServer(20605): brevent user: 0, uid: 2000
02-20 00:57:29.598 D/BreventServer(20605): brevent data directory: /data/user_de/0/com.android.shell
02-20 00:57:29.638 I/BreventServer(20605): load /data/user_de/0/com.android.shell/me.piebridge.brevent.list, size: 1
02-20 00:57:29.638 D/BreventServer(20605): loaded brevent list
02-20 00:57:29.638 D/BreventServer(20605): loaded brevent conf
02-20 00:57:29.740 D/BreventServer(20605): checking
02-20 00:57:30.104 I/BreventServer(20605): power_screen_state, tag: 2728, event: 7
02-20 00:57:30.106 I/BreventServer(20605): notification_cancel_all, tag: 2752, event: 6
02-20 00:57:30.110 I/BreventServer(20605): am_new_intent, tag: 30003, event: 2
02-20 00:57:30.111 I/BreventServer(20605): am_pause_activity, tag: 30013, event: 3
02-20 00:57:30.112 I/BreventServer(20605): am_proc_start, tag: 30014, event: 4
02-20 00:57:30.113 I/BreventServer(20605): am_switch_user, tag: 30041, event: 5
02-20 00:57:30.114 I/BreventServer(20605): am_focused_activity, tag: 30043, event: 1
02-20 00:57:30.126 D/BreventLoader(20605): Can't run brevent server
02-20 00:57:30.126 D/BreventLoader(20605): java.lang.reflect.InvocationTargetException
02-20 00:57:30.126 D/BreventLoader(20605): 	at java.lang.reflect.Method.invoke(Native Method)
02-20 00:57:30.126 D/BreventLoader(20605): 	at me.piebridge.brevent.loader.Brevent.run(Brevent.java:57)
02-20 00:57:30.126 D/BreventLoader(20605): 	at java.lang.Thread.run(Thread.java:761)
02-20 00:57:30.126 D/BreventLoader(20605): Caused by: java.net.SocketException: Permission denied
02-20 00:57:30.126 D/BreventLoader(20605): 	at java.net.ServerSocket.createImpl(ServerSocket.java:309)
02-20 00:57:30.126 D/BreventLoader(20605): 	at java.net.ServerSocket.getImpl(ServerSocket.java:258)
02-20 00:57:30.126 D/BreventLoader(20605): 	at java.net.ServerSocket.bind(ServerSocket.java:377)
02-20 00:57:30.126 D/BreventLoader(20605): 	at java.net.ServerSocket.<init>(ServerSocket.java:237)
02-20 00:57:30.126 D/BreventLoader(20605): 	at me.piebridge.brevent.server.BreventServer.main(BreventServer.java:849)
02-20 00:57:30.126 D/BreventLoader(20605): 	... 3 more
02-20 00:57:30.126 D/BreventLoader(20605): Brevent Server quit in 30 seconds, quit
02-20 00:57:30.126 E/AndroidRuntime(20605): 	at me.piebridge.brevent.loader.Brevent.run(Brevent.java:60)
02-20 00:57:30.126 E/AndroidRuntime(20605): 	at me.piebridge.brevent.loader.Brevent.run(Brevent.java:57)
02-20 00:57:30.126 E/AndroidRuntime(20605): 	at me.piebridge.brevent.server.BreventServer.main(BreventServer.java:849)
```

**Comment by liudongmiao** [comment]
Normally, the shell should have network permission. Do you use a su shell, or original shell?

duplicate #50, #72  #73

**Comment by liudongmiao** [comment]
10 天内没继续反馈，关闭。
