### ISSUE TITLE
MI4 7.1 - 没有网络权限

### ISSUE THREAD

**Issue by chm512512** [liudongmiao/Brevent#98]
```
cannot listen port, please report bug to https://github.com/liudongmiao/Brevent/issues with log below
--- crash start ---
02-20 16:34:06.810  6450  6463 E AndroidRuntime: *** FATAL EXCEPTION IN SYSTEM PROCESS: Thread-1
02-20 16:34:06.810  6450  6463 E AndroidRuntime: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException

02-20 16:34:06.810  6450  6463 E AndroidRuntime:        at me.piebridge.brevent.loader.Brevent.run(Brevent.java:60)
02-20 16:34:06.810  6450  6463 E AndroidRuntime:        at java.lang.Thread.run(Thread.java:761)
02-20 16:34:06.810  6450  6463 E AndroidRuntime: Caused by: java.lang.reflect.InvocationTargetException
02-20 16:34:06.810  6450  6463 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
02-20 16:34:06.810  6450  6463 E AndroidRuntime:        at me.piebridge.brevent.loader.Brevent.run(Brevent.java:57)
02-20 16:34:06.810  6450  6463 E AndroidRuntime:        ... 1 more
02-20 16:34:06.810  6450  6463 E AndroidRuntime: Caused by: java.net.SocketException: Permission denied
02-20 16:34:06.810  6450  6463 E AndroidRuntime:        at java.net.ServerSocket.createImpl(ServerSocket.java:309)
02-20 16:34:06.810  6450  6463 E AndroidRuntime:        at java.net.ServerSocket.getImpl(ServerSocket.java:258)
02-20 16:34:06.810  6450  6463 E AndroidRuntime:        at java.net.ServerSocket.bind(ServerSocket.java:377)
02-20 16:34:06.810  6450  6463 E AndroidRuntime:        at java.net.ServerSocket.<init>(ServerSocket.java:237)
02-20 16:34:06.810  6450  6463 E AndroidRuntime:        at me.piebridge.brevent.server.BreventServer.main(BreventServer.
java:849)
02-20 16:34:06.810  6450  6463 E AndroidRuntime:        ... 3 more
02-20 16:34:06.814  6450  6463 E AndroidRuntime: Error reporting crash
02-20 16:34:06.814  6450  6463 E AndroidRuntime: java.lang.RuntimeException: Bad file descriptor
02-20 16:34:06.814  6450  6463 E AndroidRuntime:        at android.os.BinderProxy.transactNative(Native Method)
02-20 16:34:06.814  6450  6463 E AndroidRuntime:        at android.os.BinderProxy.transact(Binder.java:615)
02-20 16:34:06.814  6450  6463 E AndroidRuntime:        at android.app.ActivityManagerProxy.handleApplicationCrash(Activ
ityManagerNative.java:5155)
02-20 16:34:06.814  6450  6463 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$UncaughtHandler.uncaughtE
xception(RuntimeInit.java:97)
02-20 16:34:06.814  6450  6463 E AndroidRuntime:        at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1068
)
02-20 16:34:06.814  6450  6463 E AndroidRuntime:        at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1063
)
02-20 16:38:55.057  9491  9509 E AndroidRuntime: *** FATAL EXCEPTION IN SYSTEM PROCESS: Thread-1
02-20 16:38:55.057  9491  9509 E AndroidRuntime: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException

02-20 16:38:55.057  9491  9509 E AndroidRuntime:        at me.piebridge.brevent.loader.Brevent.run(Brevent.java:60)
02-20 16:38:55.057  9491  9509 E AndroidRuntime:        at java.lang.Thread.run(Thread.java:761)
02-20 16:38:55.057  9491  9509 E AndroidRuntime: Caused by: java.lang.reflect.InvocationTargetException
02-20 16:38:55.057  9491  9509 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
02-20 16:38:55.057  9491  9509 E AndroidRuntime:        at me.piebridge.brevent.loader.Brevent.run(Brevent.java:57)
02-20 16:38:55.057  9491  9509 E AndroidRuntime:        ... 1 more
02-20 16:38:55.057  9491  9509 E AndroidRuntime: Caused by: java.net.SocketException: Permission denied
02-20 16:38:55.057  9491  9509 E AndroidRuntime:        at java.net.ServerSocket.createImpl(ServerSocket.java:309)
02-20 16:38:55.057  9491  9509 E AndroidRuntime:        at java.net.ServerSocket.getImpl(ServerSocket.java:258)
02-20 16:38:55.057  9491  9509 E AndroidRuntime:        at java.net.ServerSocket.bind(ServerSocket.java:377)
02-20 16:38:55.057  9491  9509 E AndroidRuntime:        at java.net.ServerSocket.<init>(ServerSocket.java:237)
02-20 16:38:55.057  9491  9509 E AndroidRuntime:        at me.piebridge.brevent.server.BreventServer.main(BreventServer.
java:849)
02-20 16:38:55.057  9491  9509 E AndroidRuntime:        ... 3 more
02-20 16:38:55.059  9491  9509 E AndroidRuntime: Error reporting crash
02-20 16:38:55.059  9491  9509 E AndroidRuntime: java.lang.RuntimeException: Bad file descriptor
02-20 16:38:55.059  9491  9509 E AndroidRuntime:        at android.os.BinderProxy.transactNative(Native Method)
02-20 16:38:55.059  9491  9509 E AndroidRuntime:        at android.os.BinderProxy.transact(Binder.java:615)
02-20 16:38:55.059  9491  9509 E AndroidRuntime:        at android.app.ActivityManagerProxy.handleApplicationCrash(Activ
ityManagerNative.java:5155)
02-20 16:38:55.059  9491  9509 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$UncaughtHandler.uncaughtE
xception(RuntimeInit.java:97)
02-20 16:38:55.059  9491  9509 E AndroidRuntime:        at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1068
)
02-20 16:38:55.059  9491  9509 E AndroidRuntime:        at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1063
)
--- crash end ---
--- brevent start ---
02-20 16:34:06.432  6450  6450 D BreventLoader: lib: /data/user_de/0/com.android.shell/brevent, loader: /data/user_de/0/
com.android.shell/brevent/libloader.so
02-20 16:34:06.437  6450  6463 D BreventServer: Brevent Server 0.7 started
02-20 16:34:06.460  6450  6463 D BreventServer: brevent user: 0, uid: 2000
02-20 16:34:06.461  6450  6463 D BreventServer: brevent data directory: /data/user_de/0/com.android.shell
02-20 16:34:06.483  6450  6463 D BreventServer: loaded brevent list
02-20 16:34:06.484  6450  6463 D BreventServer: loaded brevent conf
02-20 16:34:06.540  6450  6463 D BreventServer: checking
02-20 16:34:06.753  6450  6463 I BreventServer: power_screen_state, tag: 2728, event: 7
02-20 16:34:06.756  6450  6463 I BreventServer: notification_cancel_all, tag: 2752, event: 6
02-20 16:34:06.762  6450  6463 I BreventServer: am_new_intent, tag: 30003, event: 2
02-20 16:34:06.764  6450  6463 I BreventServer: am_pause_activity, tag: 30013, event: 3
02-20 16:34:06.765  6450  6463 I BreventServer: am_proc_start, tag: 30014, event: 4
02-20 16:34:06.767  6450  6463 I BreventServer: am_switch_user, tag: 30041, event: 5
02-20 16:34:06.767  6450  6463 I BreventServer: am_focused_activity, tag: 30043, event: 1
02-20 16:34:06.809  6450  6463 D BreventLoader: Can't run brevent server
02-20 16:34:06.809  6450  6463 D BreventLoader: java.lang.reflect.InvocationTargetException
02-20 16:34:06.809  6450  6463 D BreventLoader:         at java.lang.reflect.Method.invoke(Native Method)
02-20 16:34:06.809  6450  6463 D BreventLoader:         at me.piebridge.brevent.loader.Brevent.run(Brevent.java:57)
02-20 16:34:06.809  6450  6463 D BreventLoader:         at java.lang.Thread.run(Thread.java:761)
02-20 16:34:06.809  6450  6463 D BreventLoader: Caused by: java.net.SocketException: Permission denied
02-20 16:34:06.809  6450  6463 D BreventLoader:         at java.net.ServerSocket.createImpl(ServerSocket.java:309)
02-20 16:34:06.809  6450  6463 D BreventLoader:         at java.net.ServerSocket.getImpl(ServerSocket.java:258)
02-20 16:34:06.809  6450  6463 D BreventLoader:         at java.net.ServerSocket.bind(ServerSocket.java:377)
02-20 16:34:06.809  6450  6463 D BreventLoader:         at java.net.ServerSocket.<init>(ServerSocket.java:237)
02-20 16:34:06.809  6450  6463 D BreventLoader:         at me.piebridge.brevent.server.BreventServer.main(BreventServer.
java:849)
02-20 16:34:06.809  6450  6463 D BreventLoader:         ... 3 more
02-20 16:34:06.809  6450  6450 D BreventLoader: Brevent Server quit in 30 seconds, quit
02-20 16:38:54.473  9491  9491 D BreventLoader: lib: /data/user_de/0/com.android.shell/brevent, loader: /data/user_de/0/
com.android.shell/brevent/libloader.so
02-20 16:38:54.480  9491  9509 D BreventServer: Brevent Server 0.7 started
02-20 16:38:54.503  9491  9509 D BreventServer: brevent user: 0, uid: 2000
02-20 16:38:54.506  9491  9509 D BreventServer: brevent data directory: /data/user_de/0/com.android.shell
02-20 16:38:54.580  9491  9509 D BreventServer: loaded brevent list
02-20 16:38:54.581  9491  9509 D BreventServer: loaded brevent conf
02-20 16:38:54.736  9491  9509 D BreventServer: checking
02-20 16:38:54.996  9491  9509 I BreventServer: power_screen_state, tag: 2728, event: 7
02-20 16:38:54.999  9491  9509 I BreventServer: notification_cancel_all, tag: 2752, event: 6
02-20 16:38:55.022  9491  9509 I BreventServer: am_new_intent, tag: 30003, event: 2
02-20 16:38:55.027  9491  9509 I BreventServer: am_pause_activity, tag: 30013, event: 3
02-20 16:38:55.028  9491  9509 I BreventServer: am_proc_start, tag: 30014, event: 4
02-20 16:38:55.032  9491  9509 I BreventServer: am_switch_user, tag: 30041, event: 5
02-20 16:38:55.034  9491  9509 I BreventServer: am_focused_activity, tag: 30043, event: 1
02-20 16:38:55.056  9491  9509 D BreventLoader: Can't run brevent server
02-20 16:38:55.056  9491  9509 D BreventLoader: java.lang.reflect.InvocationTargetException
02-20 16:38:55.056  9491  9509 D BreventLoader:         at java.lang.reflect.Method.invoke(Native Method)
02-20 16:38:55.056  9491  9509 D BreventLoader:         at me.piebridge.brevent.loader.Brevent.run(Brevent.java:57)
02-20 16:38:55.056  9491  9509 D BreventLoader:         at java.lang.Thread.run(Thread.java:761)
02-20 16:38:55.056  9491  9509 D BreventLoader: Caused by: java.net.SocketException: Permission denied
02-20 16:38:55.056  9491  9509 D BreventLoader:         at java.net.ServerSocket.createImpl(ServerSocket.java:309)
02-20 16:38:55.056  9491  9509 D BreventLoader:         at java.net.ServerSocket.getImpl(ServerSocket.java:258)
02-20 16:38:55.056  9491  9509 D BreventLoader:         at java.net.ServerSocket.bind(ServerSocket.java:377)
02-20 16:38:55.056  9491  9509 D BreventLoader:         at java.net.ServerSocket.<init>(ServerSocket.java:237)
02-20 16:38:55.056  9491  9509 D BreventLoader:         at me.piebridge.brevent.server.BreventServer.main(BreventServer.
java:849)
02-20 16:38:55.056  9491  9509 D BreventLoader:         ... 3 more
02-20 16:38:55.058  9491  9491 D BreventLoader: Brevent Server quit in 30 seconds, quit
--- brevent end ---
cannot listen port, please report bug to https://github.com/liudongmiao/Brevent/issues with log above
```

**Comment by liudongmiao** [comment]
同 #50, #72, #73, #89 

你是通过电脑输入的，还是怎么样？
执行命令之前，运行下 `id` 吧

**Comment by chm512512** [comment]
电脑，用的还是su shell

**Comment by liudongmiao** [comment]
先弄个普通 shell 吧。我怀疑 su 的实现。你输入 su shell 之后，运行下 id 吧。

**Comment by liudongmiao** [comment]
早先，我限定了id与context，我在模拟器里，没有问题。
但好几例都是没有网络权限，我无法处理。

这个真的不需要 root shell，而 root 并不是真正的有权限。

**Comment by chm512512** [comment]
F:\Download\Android\adb>adb -d shell /data/app/me.piebridge.brevent-1/lib/arm/libbootstrap.so
* daemon not running. starting it now on port 5037 *
* daemon started successfully *
please run with 'su shell /data/app/me.piebridge.brevent-1/lib/arm/libbootstrap.so'


但是不给不让用额

**Comment by chm512512** [comment]
F:\Download\Android\adb>adb shell id
uid=0(root) gid=0(root) groups=0(root),1004(input),1007(log),1011(adb),1015(sdcard_rw),1028(sdcard_
,3002(net_bt),3003(inet),3006(net_bw_stats),3009(readproc) context=u:r:su:s0``

**Comment by chm512512** [comment]
不行就去用补丁版好了，强迫症也不喜欢相互唤醒，任务列表基本为空。。。。。
用完就销毁。。。。233333

**Comment by chm512512** [comment]
F:\Download\Android\adb>adb shell
cancro:/ # id
id
uid=0(root) gid=0(root) groups=0(root),1004(input),1007(log),1011(adb),1015(sdcard_rw),1028(sdcard_r),3001(net_bt_admin)
,3002(net_bt),3003(inet),3006(net_bw_stats),3009(readproc) context=u:r:su:s0
cancro:/ # stop adbd && setprop service.adb.root 0 && start adbd &
stop adbd && setprop service.adb.root 0 && start adbd &
[1] 25995
cancro:/ #
F:\Download\Android\adb>adb shell
cancro:/ $ data/app/me.piebridge.brevent-1/lib/arm/libbootstrap.so
data/app/me.piebridge.brevent-1/lib/arm/libbootstrap.so
checking....successfully
if you find any issues, please report bug to https://github.com/liudongmiao/Brevent/issues with log
for crash log: logcat -b crash -d
for brevent log: logcat -b main -d -s BreventLoader BreventServer


自己弄好了.... 等我测试一下能不能正常使用再回复~

**Comment by liudongmiao** [comment]
先运行下  adb unroot，然后执行下看看？

**Comment by chm512512** [comment]
没有这个命令，试过了。
stop adbd && setprop service.adb.root 0 && start adbd &
这个可以用

**Comment by liudongmiao** [comment]
我的意思是，电脑端执行 adb unroot，一般这个命令，和你所列的事情差不多。
如果没有，你可能需要更新  adb 的版本。
